"""baseline schema

Regenerated on 2026-10-01 for D-01..D-03 before any deployment existed (no data to
migrate). From now on every change is a new revision.

Revision ID: 0001
Revises:
Create Date: 2026-10-01 11:36:53.608666
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


# Must equal pitquant.db.models.IMMUTABLE_TABLES (checked by tests/integration/test_postgres.py).
IMMUTABLE_TABLES = (
    "raw_records",
    "feature_snapshots",
    "predictions",
    "live_predictions",
    "backtest_observations",
    "realized_returns",
    "holdout_access_log",
    "holdout_evaluations",
    "raw_source_archive",
    "sec_filings",
    "fundamental_facts",
    "index_events",
    "membership_builds",
    "index_membership",
)


def _install_immutability_triggers() -> None:
    """ADR-0010: append-only tables reject UPDATE/DELETE even from raw SQL (PostgreSQL)."""
    if op.get_bind().dialect.name != "postgresql":
        return
    op.execute(
        """
        CREATE OR REPLACE FUNCTION pitquant_forbid_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION 'table % is append-only (ADR-0010)', TG_TABLE_NAME
                USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$ LANGUAGE plpgsql;
        """
    )
    for t in IMMUTABLE_TABLES:
        op.execute(
            f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
            f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
        )
    # A frozen model version can never be modified.
    op.execute(
        """
        CREATE OR REPLACE FUNCTION pitquant_forbid_frozen_model_change() RETURNS trigger AS $$
        BEGIN
            IF OLD.frozen THEN
                RAISE EXCEPTION 'model_version % is frozen', OLD.model_version;
            END IF;
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql;
        CREATE TRIGGER model_versions_frozen BEFORE UPDATE OR DELETE ON model_versions
            FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_frozen_model_change();
        """
    )


def _drop_immutability_triggers() -> None:
    if op.get_bind().dialect.name != "postgresql":
        return
    for t in IMMUTABLE_TABLES:
        op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    op.execute("DROP TRIGGER IF EXISTS model_versions_frozen ON model_versions;")
    op.execute("DROP FUNCTION IF EXISTS pitquant_forbid_mutation();")
    op.execute("DROP FUNCTION IF EXISTS pitquant_forbid_frozen_model_change();")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "benchmarks",
        sa.Column("benchmark_code", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("return_type", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("index_code", sa.String(length=20), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.CheckConstraint(
            "return_type IN ('TR','NTR')", name=op.f("ck_benchmarks_total_return_only")
        ),
        sa.PrimaryKeyConstraint("benchmark_code", name=op.f("pk_benchmarks")),
    )
    op.create_table(
        "data_sources",
        sa.Column("source_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("provider_type", sa.String(length=50), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("is_point_in_time", sa.Boolean(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("source_id", name=op.f("pk_data_sources")),
        sa.UniqueConstraint("name", name=op.f("uq_data_sources_name")),
    )
    op.create_table(
        "issuers",
        sa.Column("issuer_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.PrimaryKeyConstraint("issuer_id", name=op.f("pk_issuers")),
    )
    op.create_table(
        "membership_builds",
        sa.Column("build_id", sa.String(length=36), nullable=False),
        sa.Column("index_code", sa.String(length=20), nullable=False),
        sa.Column("membership_source", sa.String(length=100), nullable=False),
        sa.Column("source_confidence", sa.String(length=40), nullable=False),
        sa.Column("raw_source_hash", sa.String(length=64), nullable=False),
        sa.Column("events_hash", sa.String(length=64), nullable=False),
        sa.Column("n_events", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("report", sa.JSON(), nullable=False),
        sa.Column("built_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("build_id", name=op.f("pk_membership_builds")),
    )
    op.create_table(
        "models",
        sa.Column("model_id", sa.String(length=50), nullable=False),
        sa.Column("horizon", sa.String(length=5), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("role", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("model_id", name=op.f("pk_models")),
    )
    op.create_table(
        "raw_source_archive",
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=100), nullable=False),
        sa.Column("source_identifier", sa.String(length=1000), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("mime_type", sa.String(length=100), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("storage_uri", sa.String(length=500), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("archive_id", name=op.f("pk_raw_source_archive")),
    )
    with op.batch_alter_table("raw_source_archive", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_raw_source_archive_sha256"), ["sha256"], unique=False)

    op.create_table(
        "benchmark_levels",
        sa.Column("benchmark_code", sa.String(length=30), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("level", sa.Float(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["benchmark_code"],
            ["benchmarks.benchmark_code"],
            name=op.f("fk_benchmark_levels_benchmark_code_benchmarks"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_benchmark_levels_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("benchmark_code", "session_date", name=op.f("pk_benchmark_levels")),
    )
    op.create_table(
        "macro_data",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("series_code", sa.String(length=50), nullable=False),
        sa.Column("observation_date", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_macro_data_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_macro_data")),
        sa.UniqueConstraint(
            "series_code",
            "observation_date",
            "available_at",
            name=op.f("uq_macro_data_series_code_observation_date_available_at"),
        ),
    )
    with op.batch_alter_table("macro_data", schema=None) as batch_op:
        batch_op.create_index(
            "ix_macro_asof", ["series_code", "observation_date", "available_at"], unique=False
        )

    op.create_table(
        "model_versions",
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("model_id", sa.String(length=50), nullable=False),
        sa.Column("scoring_version", sa.String(length=50), nullable=False),
        sa.Column("feature_version", sa.String(length=50), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("artifact_uri", sa.String(length=500), nullable=True),
        sa.Column("trained_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("frozen", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_id"], ["models.model_id"], name=op.f("fk_model_versions_model_id_models")
        ),
        sa.PrimaryKeyConstraint("model_version", name=op.f("pk_model_versions")),
    )
    op.create_table(
        "raw_records",
        sa.Column("raw_record_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("original_identifier", sa.String(length=200), nullable=False),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_raw_records_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("raw_record_id", name=op.f("pk_raw_records")),
        sa.UniqueConstraint(
            "source_id",
            "original_identifier",
            "payload_hash",
            name=op.f("uq_raw_records_source_id_original_identifier_payload_hash"),
        ),
    )
    op.create_table(
        "securities",
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("issuer_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("listing_start", sa.Date(), nullable=True),
        sa.Column("listing_end", sa.Date(), nullable=True),
        sa.Column("delisted", sa.Boolean(), nullable=False),
        sa.Column("delisting_reason", sa.String(length=30), nullable=True),
        sa.Column("acquirer_security_id", sa.String(length=36), nullable=True),
        sa.Column("successor_security_id", sa.String(length=36), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "listing_end IS NULL OR listing_start IS NULL OR listing_end >= listing_start",
            name=op.f("ck_securities_listing_order"),
        ),
        sa.ForeignKeyConstraint(
            ["acquirer_security_id"],
            ["securities.security_id"],
            name=op.f("fk_securities_acquirer_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"], ["issuers.issuer_id"], name=op.f("fk_securities_issuer_id_issuers")
        ),
        sa.ForeignKeyConstraint(
            ["successor_security_id"],
            ["securities.security_id"],
            name=op.f("fk_securities_successor_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("security_id", name=op.f("pk_securities")),
    )
    op.create_table(
        "analyst_estimates",
        sa.Column("estimate_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("metric", sa.String(length=30), nullable=False),
        sa.Column("target_period_end", sa.Date(), nullable=False),
        sa.Column("statistic", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_analyst_estimates_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_analyst_estimates_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("estimate_id", name=op.f("pk_analyst_estimates")),
    )
    with op.batch_alter_table("analyst_estimates", schema=None) as batch_op:
        batch_op.create_index(
            "ix_estimate_asof",
            ["security_id", "metric", "target_period_end", "available_at"],
            unique=False,
        )

    op.create_table(
        "backtest_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("config", sa.JSON(), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("universe_codes", sa.JSON(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("frequency", sa.String(length=20), nullable=False),
        sa.Column("overlapping", sa.Boolean(), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("touches_holdout", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("report", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_backtest_runs_model_version_model_versions"),
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_backtest_runs")),
    )
    op.create_table(
        "corporate_actions",
        sa.Column("action_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("action_type", sa.String(length=30), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("ratio", sa.Float(), nullable=True),
        sa.Column("cash_amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("target_security_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_corporate_actions_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_corporate_actions_source_id_data_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["target_security_id"],
            ["securities.security_id"],
            name=op.f("fk_corporate_actions_target_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("action_id", name=op.f("pk_corporate_actions")),
    )
    with op.batch_alter_table("corporate_actions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_corporate_actions_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "data_quality_issues",
        sa.Column("issue_id", sa.String(length=36), nullable=False),
        sa.Column("entity", sa.String(length=50), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("check_name", sa.String(length=100), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("detected_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw_record_id", sa.String(length=36), nullable=True),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.raw_record_id"],
            name=op.f("fk_data_quality_issues_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_data_quality_issues_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("issue_id", name=op.f("pk_data_quality_issues")),
    )
    op.create_table(
        "dividends",
        sa.Column("dividend_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("dividend_type", sa.String(length=30), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ex_date", sa.Date(), nullable=False),
        sa.Column("pay_date", sa.Date(), nullable=True),
        sa.Column("gross_amount", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("gross_amount >= 0", name=op.f("ck_dividends_non_negative")),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_dividends_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_dividends_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("dividend_id", name=op.f("pk_dividends")),
        sa.UniqueConstraint(
            "security_id",
            "ex_date",
            "dividend_type",
            "source_id",
            name=op.f("uq_dividends_security_id_ex_date_dividend_type_source_id"),
        ),
    )
    with op.batch_alter_table("dividends", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_dividends_security_id"), ["security_id"], unique=False)

    op.create_table(
        "experiments",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=True),
        sa.Column("baseline_model_version", sa.String(length=80), nullable=True),
        sa.Column("n_variants", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_experiments_model_version_model_versions"),
        ),
        sa.PrimaryKeyConstraint("experiment_id", name=op.f("pk_experiments")),
    )
    op.create_table(
        "feature_snapshots",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("feature_version", sa.String(length=50), nullable=False),
        sa.Column("data_version", sa.String(length=50), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("availability", sa.JSON(), nullable=False),
        sa.Column("missing_mask", sa.JSON(), nullable=False),
        sa.Column("imputed_mask", sa.JSON(), nullable=False),
        sa.Column("dq_warnings", sa.JSON(), nullable=False),
        sa.Column("max_available_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "max_available_at IS NULL OR max_available_at <= as_of",
            name=op.f("ck_feature_snapshots_no_lookahead"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_feature_snapshots_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_feature_snapshots")),
    )
    with op.batch_alter_table("feature_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_snapshot_lookup",
            ["security_id", "as_of", "feature_version", "data_version"],
            unique=False,
        )

    op.create_table(
        "financial_statements",
        sa.Column("statement_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("statement_type", sa.String(length=20), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("filing_ref", sa.String(length=100), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("raw_record_id", sa.String(length=36), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "available_at >= published_at",
            name=op.f("ck_financial_statements_available_after_publication"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.raw_record_id"],
            name=op.f("fk_financial_statements_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_financial_statements_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_financial_statements_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("statement_id", name=op.f("pk_financial_statements")),
    )
    with op.batch_alter_table("financial_statements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_financial_statements_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "holdout_access_log",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("requested_by", sa.String(length=100), nullable=False),
        sa.Column("accessed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_holdout_access_log_model_version_model_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_holdout_access_log")),
    )
    op.create_table(
        "identifier_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("id_type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_identifier_history_interval")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_identifier_history_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_identifier_history")),
    )
    with op.batch_alter_table("identifier_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identifier_history_security_id"), ["security_id"], unique=False
        )
        batch_op.create_index(
            "ix_identifier_lookup", ["id_type", "value", "valid_from"], unique=False
        )

    op.create_table(
        "index_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("index_code", sa.String(length=20), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("parent_event_id", sa.String(length=36), nullable=True),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("new_ticker", sa.String(length=20), nullable=True),
        sa.Column("identifier", sa.String(length=20), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reason", sa.String(length=300), nullable=True),
        sa.Column("membership_source", sa.String(length=100), nullable=False),
        sa.Column("source_event_id", sa.String(length=200), nullable=False),
        sa.Column("source_confidence", sa.String(length=40), nullable=False),
        sa.Column("raw_source_hash", sa.String(length=64), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('INDEX_ADD','INDEX_DELETE','TICKER_CHANGE','ORDINARY_REVIEW','EXTRAORDINARY_REVIEW','INITIAL_SNAPSHOT')",
            name=op.f("ck_index_events_event_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_index_events_archive_id_raw_source_archive"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_event_id"],
            ["index_events.event_id"],
            name=op.f("fk_index_events_parent_event_id_index_events"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_index_events_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_index_events")),
        sa.UniqueConstraint(
            "membership_source",
            "source_event_id",
            "raw_source_hash",
            name=op.f("uq_index_events_membership_source_source_event_id_raw_source_hash"),
        ),
    )
    with op.batch_alter_table("index_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_index_events_seq",
            ["index_code", "membership_source", "effective_date"],
            unique=False,
        )

    op.create_table(
        "prices",
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("open", sa.Float(), nullable=True),
        sa.Column("high", sa.Float(), nullable=True),
        sa.Column("low", sa.Float(), nullable=True),
        sa.Column("close", sa.Float(), nullable=False),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("bar_close_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("close > 0", name=op.f("ck_prices_positive_close")),
        sa.CheckConstraint(
            "high IS NULL OR low IS NULL OR high >= low", name=op.f("ck_prices_high_ge_low")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_prices_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["data_sources.source_id"], name=op.f("fk_prices_source_id_data_sources")
        ),
        sa.PrimaryKeyConstraint("security_id", "session_date", "source_id", name=op.f("pk_prices")),
    )
    op.create_table(
        "provider_keys",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("provider_key", sa.String(length=100), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_provider_keys_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_provider_keys_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_keys")),
        sa.UniqueConstraint(
            "source_id", "provider_key", name=op.f("uq_provider_keys_source_id_provider_key")
        ),
    )
    op.create_table(
        "sec_filings",
        sa.Column("accession_number", sa.String(length=25), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("form", sa.String(length=20), nullable=False),
        sa.Column("is_amendment", sa.Boolean(), nullable=False),
        sa.Column("filed_date", sa.Date(), nullable=False),
        sa.Column("report_period", sa.Date(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submissions_acceptance_raw", sa.String(length=40), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("availability_policy", sa.String(length=40), nullable=False),
        sa.Column("primary_document", sa.String(length=300), nullable=True),
        sa.Column("header_archive_id", sa.String(length=36), nullable=False),
        sa.Column("xbrl_archive_id", sa.String(length=36), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "available_at >= accepted_at", name=op.f("ck_sec_filings_available_after_acceptance")
        ),
        sa.ForeignKeyConstraint(
            ["header_archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_sec_filings_header_archive_id_raw_source_archive"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_sec_filings_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["xbrl_archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_sec_filings_xbrl_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("accession_number", name=op.f("pk_sec_filings")),
    )
    with op.batch_alter_table("sec_filings", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sec_filings_cik"), ["cik"], unique=False)

    op.create_table(
        "sector_classification",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("scheme", sa.String(length=20), nullable=False),
        sa.Column("sector", sa.String(length=100), nullable=False),
        sa.Column("industry_group", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=100), nullable=True),
        sa.Column("sub_industry", sa.String(length=100), nullable=True),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_sector_classification_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sector_classification")),
    )
    with op.batch_alter_table("sector_classification", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sector_classification_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "ticker_history",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_ticker_history_interval")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_ticker_history_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_ticker_history_source_id_data_sources"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ticker_history")),
    )
    with op.batch_alter_table("ticker_history", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ticker_history_security_id"), ["security_id"], unique=False
        )
        batch_op.create_index(
            "ix_ticker_lookup", ["ticker", "exchange", "valid_from"], unique=False
        )

    op.create_table(
        "fundamental_facts",
        sa.Column("fact_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("taxonomy", sa.String(length=30), nullable=False),
        sa.Column("concept", sa.String(length=200), nullable=False),
        sa.Column("fiscal_period", sa.String(length=10), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=30), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revision_id", sa.Integer(), nullable=False),
        sa.Column("cik", sa.String(length=10), nullable=True),
        sa.Column("accession_number", sa.String(length=25), nullable=True),
        sa.Column("form", sa.String(length=20), nullable=True),
        sa.Column("filed_date", sa.Date(), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_amendment", sa.Boolean(), nullable=False),
        sa.Column("source_document", sa.String(length=500), nullable=True),
        sa.Column("statement_id", sa.String(length=36), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column("raw_record_id", sa.String(length=36), nullable=True),
        sa.Column("ingested_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "accepted_at IS NULL OR available_at >= accepted_at",
            name=op.f("ck_fundamental_facts_available_after_acceptance"),
        ),
        sa.ForeignKeyConstraint(
            ["accession_number"],
            ["sec_filings.accession_number"],
            name=op.f("fk_fundamental_facts_accession_number_sec_filings"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_record_id"],
            ["raw_records.raw_record_id"],
            name=op.f("fk_fundamental_facts_raw_record_id_raw_records"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_fundamental_facts_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["data_sources.source_id"],
            name=op.f("fk_fundamental_facts_source_id_data_sources"),
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["financial_statements.statement_id"],
            name=op.f("fk_fundamental_facts_statement_id_financial_statements"),
        ),
        sa.PrimaryKeyConstraint("fact_id", name=op.f("pk_fundamental_facts")),
        sa.UniqueConstraint(
            "security_id",
            "taxonomy",
            "concept",
            "unit",
            "period_start",
            "period_end",
            "fiscal_period",
            "revision_id",
            "accession_number",
            "source_id",
            name=op.f(
                "uq_fundamental_facts_security_id_taxonomy_concept_unit_period_start_period_end_fiscal_period_revision_id_accession_number_source_id"
            ),
        ),
    )
    with op.batch_alter_table("fundamental_facts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_fact_asof", ["security_id", "concept", "period_end", "available_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_fundamental_facts_accession_number"), ["accession_number"], unique=False
        )

    op.create_table(
        "holdout_evaluations",
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("access_id", sa.String(length=36), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("holdout_start", sa.Date(), nullable=False),
        sa.Column("holdout_end", sa.Date(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("n_observations", sa.Integer(), nullable=False),
        sa.Column("metrics_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_id"],
            ["holdout_access_log.id"],
            name=op.f("fk_holdout_evaluations_access_id_holdout_access_log"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_holdout_evaluations_model_version_model_versions"),
        ),
        sa.PrimaryKeyConstraint("evaluation_id", name=op.f("pk_holdout_evaluations")),
        sa.UniqueConstraint("access_id", name=op.f("uq_holdout_evaluations_access_id")),
    )
    op.create_table(
        "index_membership",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("build_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("index_code", sa.String(length=20), nullable=False),
        sa.Column("ticker_at_inclusion", sa.String(length=20), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("inclusion_reason", sa.String(length=300), nullable=True),
        sa.Column("exclusion_reason", sa.String(length=300), nullable=True),
        sa.Column("announced_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("membership_source", sa.String(length=100), nullable=False),
        sa.Column("source_event_id", sa.String(length=36), nullable=False),
        sa.Column("exclusion_event_id", sa.String(length=36), nullable=True),
        sa.Column("source_confidence", sa.String(length=40), nullable=False),
        sa.Column("raw_source_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from",
            name=op.f("ck_index_membership_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["membership_builds.build_id"],
            name=op.f("fk_index_membership_build_id_membership_builds"),
        ),
        sa.ForeignKeyConstraint(
            ["exclusion_event_id"],
            ["index_events.event_id"],
            name=op.f("fk_index_membership_exclusion_event_id_index_events"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_index_membership_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["source_event_id"],
            ["index_events.event_id"],
            name=op.f("fk_index_membership_source_event_id_index_events"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_index_membership")),
    )
    with op.batch_alter_table("index_membership", schema=None) as batch_op:
        batch_op.create_index(
            "ix_membership_asof",
            ["build_id", "index_code", "effective_from", "effective_to"],
            unique=False,
        )

    op.create_table(
        "predictions",
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("execution_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon", sa.String(length=5), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("signal", sa.String(length=4), nullable=False),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column("expected_excess_return", sa.Float(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("scores", sa.JSON(), nullable=False),
        sa.Column("explanation", sa.JSON(), nullable=False),
        sa.Column("data_version", sa.String(length=50), nullable=False),
        sa.Column("feature_version", sa.String(length=50), nullable=False),
        sa.Column("scoring_version", sa.String(length=50), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("code_version", sa.String(length=64), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("supersedes_id", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "signal IN ('BUY','HOLD','SELL')", name=op.f("ck_predictions_signal_values")
        ),
        sa.CheckConstraint(
            "execution_at > as_of", name=op.f("ck_predictions_execution_after_signal")
        ),
        sa.CheckConstraint(
            "probability IS NULL OR (probability >= 0 AND probability <= 1)",
            name=op.f("ck_predictions_prob_range"),
        ),
        sa.ForeignKeyConstraint(
            ["model_version"],
            ["model_versions.model_version"],
            name=op.f("fk_predictions_model_version_model_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_predictions_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["feature_snapshots.snapshot_id"],
            name=op.f("fk_predictions_snapshot_id_feature_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["predictions.prediction_id"],
            name=op.f("fk_predictions_supersedes_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_predictions")),
    )
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_prediction_lookup",
            ["security_id", "as_of", "horizon", "model_version"],
            unique=False,
        )

    op.create_table(
        "backtest_observations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon", sa.String(length=5), nullable=False),
        sa.Column("t_exec", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "label_available_at >= label_end",
            name=op.f("ck_backtest_observations_label_available_after_end"),
        ),
        sa.CheckConstraint(
            "label_end > t_exec", name=op.f("ck_backtest_observations_label_after_exec")
        ),
        sa.CheckConstraint(
            "t_exec > as_of", name=op.f("ck_backtest_observations_exec_after_signal")
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.prediction_id"],
            name=op.f("fk_backtest_observations_prediction_id_predictions"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["backtest_runs.run_id"],
            name=op.f("fk_backtest_observations_run_id_backtest_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_backtest_observations_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_backtest_observations")),
    )
    with op.batch_alter_table("backtest_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_backtest_observations_run_id"), ["run_id"], unique=False
        )

    op.create_table(
        "error_analysis",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("hypothesis", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.prediction_id"],
            name=op.f("fk_error_analysis_prediction_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_error_analysis")),
    )
    op.create_table(
        "live_predictions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("registered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evaluation_due_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "evaluation_due_at > registered_at", name=op.f("ck_live_predictions_due_in_future")
        ),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.prediction_id"],
            name=op.f("fk_live_predictions_prediction_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_live_predictions")),
        sa.UniqueConstraint("prediction_id", name=op.f("uq_live_predictions_prediction_id")),
    )
    op.create_table(
        "realized_returns",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("horizon", sa.String(length=5), nullable=False),
        sa.Column("t_exec", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("label_available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("stock_total_return", sa.Float(), nullable=False),
        sa.Column("market_total_return", sa.Float(), nullable=False),
        sa.Column("sector_total_return", sa.Float(), nullable=True),
        sa.Column("market_excess_return", sa.Float(), nullable=False),
        sa.Column("sector_excess_return", sa.Float(), nullable=True),
        sa.Column("absolute_return", sa.Float(), nullable=False),
        sa.Column("volatility", sa.Float(), nullable=True),
        sa.Column("downside_volatility", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("max_adverse_excursion", sa.Float(), nullable=True),
        sa.Column("max_favorable_excursion", sa.Float(), nullable=True),
        sa.Column("delisted_during_horizon", sa.Boolean(), nullable=False),
        sa.Column("return_currency", sa.String(length=3), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["predictions.prediction_id"],
            name=op.f("fk_realized_returns_prediction_id_predictions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_realized_returns")),
        sa.UniqueConstraint(
            "prediction_id", "horizon", name=op.f("uq_realized_returns_prediction_id_horizon")
        ),
    )
    # ### end Alembic commands ###
    _install_immutability_triggers()


def downgrade() -> None:
    _drop_immutability_triggers()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("realized_returns")
    op.drop_table("live_predictions")
    op.drop_table("error_analysis")
    with op.batch_alter_table("backtest_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_backtest_observations_run_id"))

    op.drop_table("backtest_observations")
    with op.batch_alter_table("predictions", schema=None) as batch_op:
        batch_op.drop_index("ix_prediction_lookup")

    op.drop_table("predictions")
    with op.batch_alter_table("index_membership", schema=None) as batch_op:
        batch_op.drop_index("ix_membership_asof")

    op.drop_table("index_membership")
    op.drop_table("holdout_evaluations")
    with op.batch_alter_table("fundamental_facts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fundamental_facts_accession_number"))
        batch_op.drop_index("ix_fact_asof")

    op.drop_table("fundamental_facts")
    with op.batch_alter_table("ticker_history", schema=None) as batch_op:
        batch_op.drop_index("ix_ticker_lookup")
        batch_op.drop_index(batch_op.f("ix_ticker_history_security_id"))

    op.drop_table("ticker_history")
    with op.batch_alter_table("sector_classification", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sector_classification_security_id"))

    op.drop_table("sector_classification")
    with op.batch_alter_table("sec_filings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sec_filings_cik"))

    op.drop_table("sec_filings")
    op.drop_table("provider_keys")
    op.drop_table("prices")
    with op.batch_alter_table("index_events", schema=None) as batch_op:
        batch_op.drop_index("ix_index_events_seq")

    op.drop_table("index_events")
    with op.batch_alter_table("identifier_history", schema=None) as batch_op:
        batch_op.drop_index("ix_identifier_lookup")
        batch_op.drop_index(batch_op.f("ix_identifier_history_security_id"))

    op.drop_table("identifier_history")
    op.drop_table("holdout_access_log")
    with op.batch_alter_table("financial_statements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_financial_statements_security_id"))

    op.drop_table("financial_statements")
    with op.batch_alter_table("feature_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_snapshot_lookup")

    op.drop_table("feature_snapshots")
    op.drop_table("experiments")
    with op.batch_alter_table("dividends", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_dividends_security_id"))

    op.drop_table("dividends")
    op.drop_table("data_quality_issues")
    with op.batch_alter_table("corporate_actions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corporate_actions_security_id"))

    op.drop_table("corporate_actions")
    op.drop_table("backtest_runs")
    with op.batch_alter_table("analyst_estimates", schema=None) as batch_op:
        batch_op.drop_index("ix_estimate_asof")

    op.drop_table("analyst_estimates")
    op.drop_table("securities")
    op.drop_table("raw_records")
    op.drop_table("model_versions")
    with op.batch_alter_table("macro_data", schema=None) as batch_op:
        batch_op.drop_index("ix_macro_asof")

    op.drop_table("macro_data")
    op.drop_table("benchmark_levels")
    with op.batch_alter_table("raw_source_archive", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_raw_source_archive_sha256"))

    op.drop_table("raw_source_archive")
    op.drop_table("models")
    op.drop_table("membership_builds")
    op.drop_table("issuers")
    op.drop_table("data_sources")
    op.drop_table("benchmarks")
    # ### end Alembic commands ###
