"""issuer/security identity, identity snapshots and resolution, normalized corporate actions

ADR-0020 (issuer != security, ANCV snapshots as evidence, IdentityResolutionEngine) and
ADR-0021 (provider-neutral corporate actions; vendor adjusted prices for QA only).
Existing CNMV rows keep their CIF pseudo-security; new CNMV rows carry issuer_id. A
downgrade fails if issuer-only rows exist (security_id becomes NOT NULL again).

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-01 21:02:29.621500
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None

# Append-only tables introduced by this revision (union with earlier lists = models).
ADDED_IMMUTABLE_TABLES = (
    "security_identity_snapshots",
    "identity_resolution_runs",
    "membership_identity_segments",
    "corporate_action_events",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "identity_resolution_runs",
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("index_code", sa.String(length=20), nullable=False),
        sa.Column("build_id", sa.String(length=36), nullable=False),
        sa.Column("engine_version", sa.String(length=30), nullable=False),
        sa.Column("inputs_hash", sa.String(length=64), nullable=False),
        sa.Column("canonical_start", sa.Date(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["membership_builds.build_id"],
            name=op.f("fk_identity_resolution_runs_build_id_membership_builds"),
        ),
        sa.PrimaryKeyConstraint("run_id", name=op.f("pk_identity_resolution_runs")),
    )
    with op.batch_alter_table("identity_resolution_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_identity_resolution_runs_build_id"), ["build_id"], unique=False
        )

    op.create_table(
        "issuer_identifiers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("issuer_id", sa.String(length=36), nullable=False),
        sa.Column("id_type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(length=30), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=False),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_to > valid_from", name=op.f("ck_issuer_identifiers_interval")
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.issuer_id"],
            name=op.f("fk_issuer_identifiers_issuer_id_issuers"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issuer_identifiers")),
    )
    with op.batch_alter_table("issuer_identifiers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_issuer_identifier_lookup", ["id_type", "value", "valid_from"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_issuer_identifiers_issuer_id"), ["issuer_id"], unique=False
        )

    op.create_table(
        "corporate_action_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("announcement_date", sa.Date(), nullable=True),
        sa.Column("ex_date", sa.Date(), nullable=True),
        sa.Column("record_date", sa.Date(), nullable=True),
        sa.Column("payment_date", sa.Date(), nullable=True),
        sa.Column("effective_date", sa.Date(), nullable=True),
        sa.Column("available_at", UTCDateTime(), nullable=False),
        sa.Column("ratio", sa.Float(), nullable=True),
        sa.Column("cash_amount", sa.Float(), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("target_security_id", sa.String(length=36), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("source_tier", sa.String(length=20), nullable=False),
        sa.Column("provider_event_id", sa.String(length=200), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('CASH_DIVIDEND','SPECIAL_DIVIDEND','STOCK_DIVIDEND','SPLIT','REVERSE_SPLIT','RIGHTS_ISSUE','SCRIP_DIVIDEND','SPINOFF','CASH_ACQUISITION','STOCK_ACQUISITION','MERGER','DELISTING','BANKRUPTCY','TICKER_CHANGE','EXCHANGE_CHANGE','LISTING','RETURN_OF_CAPITAL','ISIN_CHANGE')",
            name=op.f("ck_corporate_action_events_event_type_values"),
        ),
        sa.CheckConstraint(
            "source_tier IN ('OFFICIAL','VENDOR','FIXTURE')",
            name=op.f("ck_corporate_action_events_tier_values"),
        ),
        sa.CheckConstraint(
            "ratio IS NULL OR ratio > 0", name=op.f("ck_corporate_action_events_positive_ratio")
        ),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_corporate_action_events_archive_id_raw_source_archive"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_corporate_action_events_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["target_security_id"],
            ["securities.security_id"],
            name=op.f("fk_corporate_action_events_target_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_corporate_action_events")),
        sa.UniqueConstraint("provider", "provider_event_id", "source_hash", name="uq_ca_event"),
    )
    with op.batch_alter_table("corporate_action_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_corporate_action_events_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "provider_adjusted_prices",
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("session_date", sa.Date(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("adj_close", sa.Float(), nullable=False),
        sa.Column("vendor_last_updated", sa.Date(), nullable=True),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_provider_adjusted_prices_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint(
            "security_id", "session_date", "provider", name=op.f("pk_provider_adjusted_prices")
        ),
    )
    op.create_table(
        "security_identity_snapshots",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=50), nullable=False),
        sa.Column("reference_date", sa.Date(), nullable=False),
        sa.Column("scope", sa.String(length=40), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("issuer_legal_name", sa.String(length=300), nullable=False),
        sa.Column("instrument_name", sa.String(length=300), nullable=False),
        sa.Column("instrument_class", sa.String(length=10), nullable=False),
        sa.Column("cfi", sa.String(length=6), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("nominal", sa.String(length=30), nullable=True),
        sa.Column("issue_date", sa.Date(), nullable=True),
        sa.Column("issuer_id", sa.String(length=36), nullable=True),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("member_name", sa.String(length=200), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_security_identity_snapshots_archive_id_raw_source_archive"),
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.issuer_id"],
            name=op.f("fk_security_identity_snapshots_issuer_id_issuers"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_security_identity_snapshots_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_security_identity_snapshots")),
        sa.UniqueConstraint(
            "source", "reference_date", "isin", "source_hash", name="uq_ident_snap"
        ),
    )
    with op.batch_alter_table("security_identity_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_security_identity_snapshots_isin"), ["isin"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_security_identity_snapshots_reference_date"),
            ["reference_date"],
            unique=False,
        )

    op.create_table(
        "membership_identity_segments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("membership_id", sa.Integer(), nullable=False),
        sa.Column("segment_from", sa.Date(), nullable=False),
        sa.Column("segment_to", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("period_class", sa.String(length=30), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("issuer_id", sa.String(length=36), nullable=True),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.CheckConstraint(
            "status IN ('EXACT_OFFICIAL_IDENTIFIER','MULTI_SOURCE_CONFIRMED','PROVISIONAL','UNRESOLVED')",
            name=op.f("ck_membership_identity_segments_status_values"),
        ),
        sa.CheckConstraint(
            "segment_to IS NULL OR segment_to > segment_from",
            name=op.f("ck_membership_identity_segments_interval"),
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.issuer_id"],
            name=op.f("fk_membership_identity_segments_issuer_id_issuers"),
        ),
        sa.ForeignKeyConstraint(
            ["membership_id"],
            ["index_membership.id"],
            name=op.f("fk_membership_identity_segments_membership_id_index_membership"),
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["identity_resolution_runs.run_id"],
            name=op.f("fk_membership_identity_segments_run_id_identity_resolution_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_membership_identity_segments_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_membership_identity_segments")),
    )
    with op.batch_alter_table("membership_identity_segments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_membership_identity_segments_membership_id"),
            ["membership_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_membership_identity_segments_run_id"), ["run_id"], unique=False
        )

    with op.batch_alter_table("cnmv_filings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("issuer_id", sa.String(length=36), nullable=True))
        batch_op.alter_column("security_id", existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.create_index(batch_op.f("ix_cnmv_filings_issuer_id"), ["issuer_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_cnmv_filings_issuer_id_issuers"), "issuers", ["issuer_id"], ["issuer_id"]
        )

    with op.batch_alter_table("fundamental_facts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("issuer_id", sa.String(length=36), nullable=True))
        batch_op.alter_column("security_id", existing_type=sa.VARCHAR(length=36), nullable=True)
        batch_op.create_index(
            "ix_fact_issuer_asof",
            ["issuer_id", "concept", "period_end", "available_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_fundamental_facts_issuer_id"), ["issuer_id"], unique=False
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_fundamental_facts_issuer_id_issuers"),
            "issuers",
            ["issuer_id"],
            ["issuer_id"],
        )
        batch_op.create_check_constraint(
            "has_subject", "security_id IS NOT NULL OR issuer_id IS NOT NULL"
        )

    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    with op.batch_alter_table("fundamental_facts", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("ck_fundamental_facts_has_subject"), type_="check")
        batch_op.drop_constraint(
            batch_op.f("fk_fundamental_facts_issuer_id_issuers"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_fundamental_facts_issuer_id"))
        batch_op.drop_index("ix_fact_issuer_asof")
        batch_op.alter_column("security_id", existing_type=sa.VARCHAR(length=36), nullable=False)
        batch_op.drop_column("issuer_id")

    with op.batch_alter_table("cnmv_filings", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_cnmv_filings_issuer_id_issuers"), type_="foreignkey"
        )
        batch_op.drop_index(batch_op.f("ix_cnmv_filings_issuer_id"))
        batch_op.alter_column("security_id", existing_type=sa.VARCHAR(length=36), nullable=False)
        batch_op.drop_column("issuer_id")

    with op.batch_alter_table("membership_identity_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_membership_identity_segments_run_id"))
        batch_op.drop_index(batch_op.f("ix_membership_identity_segments_membership_id"))

    op.drop_table("membership_identity_segments")
    with op.batch_alter_table("security_identity_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_security_identity_snapshots_reference_date"))
        batch_op.drop_index(batch_op.f("ix_security_identity_snapshots_isin"))

    op.drop_table("security_identity_snapshots")
    op.drop_table("provider_adjusted_prices")
    with op.batch_alter_table("corporate_action_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corporate_action_events_security_id"))

    op.drop_table("corporate_action_events")
    with op.batch_alter_table("issuer_identifiers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_issuer_identifiers_issuer_id"))
        batch_op.drop_index("ix_issuer_identifier_lookup")

    op.drop_table("issuer_identifiers")
    with op.batch_alter_table("identity_resolution_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_identity_resolution_runs_build_id"))

    op.drop_table("identity_resolution_runs")
    # ### end Alembic commands ###
