"""official code-ISIN evidence

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-02 10:25:10.169678
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("official_code_isin_evidence",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "official_code_isin_evidence",
        sa.Column("evidence_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=20), nullable=False),
        sa.Column("isin", sa.String(length=12), nullable=False),
        sa.Column("observed_on", sa.Date(), nullable=False),
        sa.Column("issuer_name", sa.String(length=300), nullable=False),
        sa.Column("market", sa.String(length=100), nullable=True),
        sa.Column("source_kind", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("capture_timestamp", sa.String(length=20), nullable=True),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_official_code_isin_evidence_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("evidence_id", name=op.f("pk_official_code_isin_evidence")),
        sa.UniqueConstraint("source_sha256", "code", "isin", "observed_on", name="uq_code_isin_ev"),
    )
    with op.batch_alter_table("official_code_isin_evidence", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_official_code_isin_evidence_code"), ["code"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_official_code_isin_evidence_isin"), ["isin"], unique=False
        )

    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    with op.batch_alter_table("official_code_isin_evidence", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_official_code_isin_evidence_isin"))
        batch_op.drop_index(batch_op.f("ix_official_code_isin_evidence_code"))

    op.drop_table("official_code_isin_evidence")
    # ### end Alembic commands ###
