"""official ISIN transitions

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-02 10:38:30.051910
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0006"
down_revision = "0005"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("official_isin_transitions",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "official_isin_transitions",
        sa.Column("transition_id", sa.String(length=36), nullable=False),
        sa.Column("issuer_name", sa.String(length=300), nullable=False),
        sa.Column("old_isin", sa.String(length=12), nullable=False),
        sa.Column("new_isin", sa.String(length=12), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("continuity", sa.String(length=20), nullable=False),
        sa.Column("effective_date", sa.Date(), nullable=False),
        sa.Column("documents", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "continuity IN ('SAME_SECURITY','NEW_SECURITY')",
            name=op.f("ck_official_isin_transitions_continuity_values"),
        ),
        sa.CheckConstraint(
            "old_isin <> new_isin", name=op.f("ck_official_isin_transitions_distinct_isins")
        ),
        sa.PrimaryKeyConstraint("transition_id", name=op.f("pk_official_isin_transitions")),
        sa.UniqueConstraint("old_isin", "new_isin", "effective_date", name="uq_isin_transition"),
    )
    with op.batch_alter_table("official_isin_transitions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_official_isin_transitions_new_isin"), ["new_isin"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_official_isin_transitions_old_isin"), ["old_isin"], unique=False
        )

    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    with op.batch_alter_table("official_isin_transitions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_official_isin_transitions_old_isin"))
        batch_op.drop_index(batch_op.f("ix_official_isin_transitions_new_isin"))

    op.drop_table("official_isin_transitions")
    # ### end Alembic commands ###
