"""CA ingestion trace, security role, SEC filings issuer

Revision ID: 0007
Revises: 0006
Create Date: 2026-10-02 10:53:49.046569
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0007"
down_revision = "0006"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("corporate_action_ingestions",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corporate_action_ingestions",
        sa.Column("ingestion_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("events_found", sa.Integer(), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("detail", sa.String(length=300), nullable=True),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('COMPLETED','FAILED')",
            name=op.f("ck_corporate_action_ingestions_status_values"),
        ),
        sa.CheckConstraint(
            "period_end >= period_start", name=op.f("ck_corporate_action_ingestions_period_order")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_corporate_action_ingestions_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("ingestion_id", name=op.f("pk_corporate_action_ingestions")),
    )
    with op.batch_alter_table("corporate_action_ingestions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_corporate_action_ingestions_security_id"), ["security_id"], unique=False
        )

    with op.batch_alter_table("sec_filings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("issuer_id", sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f("ix_sec_filings_issuer_id"), ["issuer_id"], unique=False)
        batch_op.create_foreign_key(
            batch_op.f("fk_sec_filings_issuer_id_issuers"), "issuers", ["issuer_id"], ["issuer_id"]
        )

    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("role", sa.String(length=20), server_default="TRADED", nullable=False)
        )

    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    with op.batch_alter_table("securities", schema=None) as batch_op:
        batch_op.drop_column("role")

    with op.batch_alter_table("sec_filings", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_sec_filings_issuer_id_issuers"), type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_sec_filings_issuer_id"))
        batch_op.drop_column("issuer_id")

    with op.batch_alter_table("corporate_action_ingestions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_corporate_action_ingestions_security_id"))

    op.drop_table("corporate_action_ingestions")
    # ### end Alembic commands ###
