"""sp500 membership evidence

Revision ID: 0009
Revises: 0008
Create Date: 2026-10-02 12:36:51.080335
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0009"
down_revision = "0008"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("sp500_discovery_rows", "sp500_announcements", "sp500_membership_events")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sp500_announcements",
        sa.Column("announcement_row_id", sa.String(length=36), nullable=False),
        sa.Column("source_tier", sa.String(length=24), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("announcement_at", UTCDateTime(), nullable=False),
        sa.Column("stated_change_date", sa.Date(), nullable=True),
        sa.Column("timing", sa.String(length=20), nullable=False),
        sa.Column("effective_at", UTCDateTime(), nullable=True),
        sa.Column("added_ticker", sa.String(length=12), nullable=False),
        sa.Column("added_name", sa.String(length=120), nullable=False),
        sa.Column("removed_ticker", sa.String(length=12), nullable=False),
        sa.Column("removed_name", sa.String(length=120), nullable=False),
        sa.Column("reason_class", sa.String(length=30), nullable=False),
        sa.Column("excerpt", sa.String(length=500), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_sp500_announcements_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("announcement_row_id", name=op.f("pk_sp500_announcements")),
        sa.UniqueConstraint(
            "source_sha256", "added_ticker", "removed_ticker", "parser_version", name="uq_sp500_ann"
        ),
    )
    with op.batch_alter_table("sp500_announcements", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sp500_announcements_added_ticker"), ["added_ticker"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sp500_announcements_removed_ticker"), ["removed_ticker"], unique=False
        )

    op.create_table(
        "sp500_discovery_rows",
        sa.Column("row_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("row_date", sa.Date(), nullable=False),
        sa.Column("added_tickers", sa.JSON(), nullable=False),
        sa.Column("removed_tickers", sa.JSON(), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_sp500_discovery_rows_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("row_id", name=op.f("pk_sp500_discovery_rows")),
    )
    with op.batch_alter_table("sp500_discovery_rows", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sp500_discovery_rows_row_date"), ["row_date"], unique=False
        )

    op.create_table(
        "sp500_membership_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=False),
        sa.Column("discovery_row_id", sa.String(length=36), nullable=True),
        sa.Column("announcement_row_id", sa.String(length=36), nullable=True),
        sa.Column("added_ticker", sa.String(length=12), nullable=True),
        sa.Column("added_security_id", sa.String(length=36), nullable=True),
        sa.Column("removed_ticker", sa.String(length=12), nullable=True),
        sa.Column("removed_security_id", sa.String(length=36), nullable=True),
        sa.Column("announcement_at", UTCDateTime(), nullable=True),
        sa.Column("stated_change_date", sa.Date(), nullable=True),
        sa.Column("timing", sa.String(length=20), nullable=True),
        sa.Column("effective_at", UTCDateTime(), nullable=True),
        sa.Column("discovery_date", sa.Date(), nullable=True),
        sa.Column("source_tier", sa.String(length=24), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=True),
        sa.Column("raw_source_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("reason", sa.String(length=300), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('OFFICIAL_CONFIRMED','OFFICIAL_REPUBLISHED_CONFIRMED','DISCOVERY_ONLY','DATE_TBA','CONFLICT','UNRESOLVED')",
            name=op.f("ck_sp500_membership_events_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["added_security_id"],
            ["securities.security_id"],
            name=op.f("fk_sp500_membership_events_added_security_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["announcement_row_id"],
            ["sp500_announcements.announcement_row_id"],
            name=op.f("fk_sp500_membership_events_announcement_row_id_sp500_announcements"),
        ),
        sa.ForeignKeyConstraint(
            ["discovery_row_id"],
            ["sp500_discovery_rows.row_id"],
            name=op.f("fk_sp500_membership_events_discovery_row_id_sp500_discovery_rows"),
        ),
        sa.ForeignKeyConstraint(
            ["removed_security_id"],
            ["securities.security_id"],
            name=op.f("fk_sp500_membership_events_removed_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_sp500_membership_events")),
    )
    with op.batch_alter_table("sp500_membership_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sp500_membership_events_run_id"), ["run_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sp500_membership_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sp500_membership_events_run_id"))

    op.drop_table("sp500_membership_events")
    with op.batch_alter_table("sp500_discovery_rows", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sp500_discovery_rows_row_date"))

    op.drop_table("sp500_discovery_rows")
    with op.batch_alter_table("sp500_announcements", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sp500_announcements_removed_ticker"))
        batch_op.drop_index(batch_op.f("ix_sp500_announcements_added_ticker"))

    op.drop_table("sp500_announcements")
    # ### end Alembic commands ###
