"""index anchors

Revision ID: 0010
Revises: 0009
Create Date: 2026-10-02 17:59:47.229470
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0010"
down_revision = "0009"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("index_anchor_snapshots", "index_current_anchors")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "index_anchor_snapshots",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("key_level", sa.String(length=12), nullable=False),
        sa.Column("holdings", sa.JSON(), nullable=False),
        sa.Column("excluded", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_index_anchor_snapshots_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_index_anchor_snapshots")),
    )
    op.create_table(
        "index_current_anchors",
        sa.Column("anchor_id", sa.String(length=36), nullable=False),
        sa.Column("index_code", sa.String(length=20), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("key_level", sa.String(length=12), nullable=False),
        sa.Column("members", sa.JSON(), nullable=False),
        sa.Column("spy_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("ivv_snapshot_id", sa.String(length=36), nullable=True),
        sa.Column("reconciled", sa.Integer(), nullable=False),
        sa.Column("applied_events", sa.JSON(), nullable=False),
        sa.Column("differences", sa.JSON(), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('OFFICIAL_SPDJI','MULTI_SOURCE_CONFIRMED','CONFLICT','BLOCKED')",
            name=op.f("ck_index_current_anchors_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["ivv_snapshot_id"],
            ["index_anchor_snapshots.snapshot_id"],
            name=op.f("fk_index_current_anchors_ivv_snapshot_id_index_anchor_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["spy_snapshot_id"],
            ["index_anchor_snapshots.snapshot_id"],
            name=op.f("fk_index_current_anchors_spy_snapshot_id_index_anchor_snapshots"),
        ),
        sa.PrimaryKeyConstraint("anchor_id", name=op.f("pk_index_current_anchors")),
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("index_current_anchors")
    op.drop_table("index_anchor_snapshots")
    # ### end Alembic commands ###
