"""security profiles

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-02 20:19:10.475684
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0011"
down_revision = "0010"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("security_profiles",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "security_profiles",
        sa.Column("profile_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("current_ticker", sa.String(length=20), nullable=True),
        sa.Column("display_name", sa.String(length=300), nullable=False),
        sa.Column("exchange", sa.String(length=40), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("sic", sa.String(length=8), nullable=True),
        sa.Column("sic_description", sa.String(length=200), nullable=True),
        sa.Column("sector", sa.String(length=100), nullable=True),
        sa.Column("industry", sa.String(length=200), nullable=True),
        sa.Column("profile_type", sa.String(length=24), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.String(length=1000), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "profile_type IN ('STANDARD_CORPORATE','BANK','INSURER','REIT','OTHER_SPECIAL')",
            name=op.f("ck_security_profiles_profile_type_values"),
        ),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_security_profiles_archive_id_raw_source_archive"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_security_profiles_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("profile_id", name=op.f("pk_security_profiles")),
    )
    with op.batch_alter_table("security_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_security_profiles_current_ticker"), ["current_ticker"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_security_profiles_security_id"), ["security_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("security_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_security_profiles_security_id"))
        batch_op.drop_index(batch_op.f("ix_security_profiles_current_ticker"))

    op.drop_table("security_profiles")
    # ### end Alembic commands ###
