"""research lab

Revision ID: 0012
Revises: 0011
Create Date: 2026-10-02 23:28:09.019672
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0012"
down_revision = "0011"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = (
    "feature_set_versions",
    "label_definitions",
    "model_configs",
    "dataset_versions",
    "research_experiments",
    "research_folds",
    "research_predictions",
    "realized_outcomes",
    "metric_sets",
    "champion_challenger_comparisons",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_set_versions",
        sa.Column("feature_set_version_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("feature_version", sa.String(length=50), nullable=False),
        sa.Column("tag_map_version", sa.String(length=50), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("set_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("feature_set_version_id", name=op.f("pk_feature_set_versions")),
        sa.UniqueConstraint("set_hash", name=op.f("uq_feature_set_versions_set_hash")),
    )
    op.create_table(
        "label_definitions",
        sa.Column("label_definition_id", sa.String(length=36), nullable=False),
        sa.Column("label_version", sa.String(length=50), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("target_kind", sa.String(length=40), nullable=False),
        sa.Column("benchmark", sa.String(length=60), nullable=False),
        sa.Column("benchmark_type", sa.String(length=20), nullable=False),
        sa.Column("definition", sa.JSON(), nullable=False),
        sa.Column("definition_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("label_definition_id", name=op.f("pk_label_definitions")),
        sa.UniqueConstraint("definition_hash", name=op.f("uq_label_definitions_definition_hash")),
    )
    op.create_table(
        "model_configs",
        sa.Column("model_config_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("grid", sa.JSON(), nullable=False),
        sa.Column("config_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("model_config_id", name=op.f("pk_model_configs")),
        sa.UniqueConstraint("config_hash", name=op.f("uq_model_configs_config_hash")),
    )
    op.create_table(
        "dataset_versions",
        sa.Column("dataset_version_id", sa.String(length=36), nullable=False),
        sa.Column("dataset_hash", sa.String(length=64), nullable=False),
        sa.Column("universe", sa.String(length=120), nullable=False),
        sa.Column("universe_version", sa.String(length=120), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("snapshot_frequency", sa.String(length=20), nullable=False),
        sa.Column("feature_set_version_id", sa.String(length=36), nullable=False),
        sa.Column("label_definition_id", sa.String(length=36), nullable=False),
        sa.Column("benchmark", sa.String(length=60), nullable=False),
        sa.Column("n_rows", sa.Integer(), nullable=False),
        sa.Column("n_eligible", sa.Integer(), nullable=False),
        sa.Column("n_securities", sa.Integer(), nullable=False),
        sa.Column("holdout_dates_excluded", sa.Integer(), nullable=False),
        sa.Column("builder_version", sa.String(length=40), nullable=False),
        sa.Column("rows_path", sa.String(length=500), nullable=True),
        sa.Column("summary", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["feature_set_version_id"],
            ["feature_set_versions.feature_set_version_id"],
            name=op.f("fk_dataset_versions_feature_set_version_id_feature_set_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["label_definition_id"],
            ["label_definitions.label_definition_id"],
            name=op.f("fk_dataset_versions_label_definition_id_label_definitions"),
        ),
        sa.PrimaryKeyConstraint("dataset_version_id", name=op.f("pk_dataset_versions")),
        sa.UniqueConstraint("dataset_hash", name=op.f("uq_dataset_versions_dataset_hash")),
    )
    op.create_table(
        "realized_outcomes",
        sa.Column("outcome_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("decision_at", UTCDateTime(), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("label_version", sa.String(length=50), nullable=False),
        sa.Column("security_total_return", sa.Float(), nullable=True),
        sa.Column("benchmark_total_return", sa.Float(), nullable=True),
        sa.Column("excess_total_return", sa.Float(), nullable=True),
        sa.Column("outperform", sa.Boolean(), nullable=True),
        sa.Column("label_available_at", UTCDateTime(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_realized_outcomes_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("outcome_id", name=op.f("pk_realized_outcomes")),
    )
    with op.batch_alter_table("realized_outcomes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_realized_outcomes_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "research_experiments",
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("dataset_version_id", sa.String(length=36), nullable=True),
        sa.Column("dataset_hash", sa.String(length=64), nullable=True),
        sa.Column("feature_set_version_id", sa.String(length=36), nullable=False),
        sa.Column("label_definition_id", sa.String(length=36), nullable=False),
        sa.Column("model_config_id", sa.String(length=36), nullable=False),
        sa.Column("universe_version", sa.String(length=120), nullable=False),
        sa.Column("benchmark_version", sa.String(length=80), nullable=False),
        sa.Column("train_start", sa.Date(), nullable=True),
        sa.Column("train_end", sa.Date(), nullable=True),
        sa.Column("validation_start", sa.Date(), nullable=True),
        sa.Column("validation_end", sa.Date(), nullable=True),
        sa.Column("purge_months", sa.Integer(), nullable=False),
        sa.Column("embargo_months", sa.Integer(), nullable=False),
        sa.Column("window_kind", sa.String(length=12), nullable=False),
        sa.Column("seed", sa.Integer(), nullable=False),
        sa.Column("library_versions", sa.JSON(), nullable=False),
        sa.Column("spec", sa.JSON(), nullable=False),
        sa.Column("spec_hash", sa.String(length=64), nullable=False),
        sa.Column("blocked_reasons", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_version_id"],
            ["dataset_versions.dataset_version_id"],
            name=op.f("fk_research_experiments_dataset_version_id_dataset_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_set_version_id"],
            ["feature_set_versions.feature_set_version_id"],
            name=op.f("fk_research_experiments_feature_set_version_id_feature_set_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["label_definition_id"],
            ["label_definitions.label_definition_id"],
            name=op.f("fk_research_experiments_label_definition_id_label_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id"],
            ["model_configs.model_config_id"],
            name=op.f("fk_research_experiments_model_config_id_model_configs"),
        ),
        sa.PrimaryKeyConstraint("experiment_id", name=op.f("pk_research_experiments")),
        sa.UniqueConstraint("spec_hash", name=op.f("uq_research_experiments_spec_hash")),
    )
    op.create_table(
        "champion_challenger_comparisons",
        sa.Column("comparison_id", sa.String(length=36), nullable=False),
        sa.Column("champion_experiment_id", sa.String(length=36), nullable=True),
        sa.Column("challenger_experiment_id", sa.String(length=36), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("decision", sa.String(length=20), nullable=False),
        sa.Column("reviewer", sa.String(length=120), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["challenger_experiment_id"],
            ["research_experiments.experiment_id"],
            name=op.f(
                "fk_champion_challenger_comparisons_challenger_experiment_id_research_experiments"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["champion_experiment_id"],
            ["research_experiments.experiment_id"],
            name=op.f(
                "fk_champion_challenger_comparisons_champion_experiment_id_research_experiments"
            ),
        ),
        sa.PrimaryKeyConstraint("comparison_id", name=op.f("pk_champion_challenger_comparisons")),
    )
    op.create_table(
        "research_folds",
        sa.Column("fold_id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("fold_index", sa.Integer(), nullable=False),
        sa.Column("train_start", sa.Date(), nullable=False),
        sa.Column("train_end", sa.Date(), nullable=False),
        sa.Column("validation_start", sa.Date(), nullable=False),
        sa.Column("validation_end", sa.Date(), nullable=False),
        sa.Column("n_train", sa.Integer(), nullable=True),
        sa.Column("n_validation", sa.Integer(), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["research_experiments.experiment_id"],
            name=op.f("fk_research_folds_experiment_id_research_experiments"),
        ),
        sa.PrimaryKeyConstraint("fold_id", name=op.f("pk_research_folds")),
    )
    with op.batch_alter_table("research_folds", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_folds_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "metric_sets",
        sa.Column("metric_set_id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("fold_id", sa.String(length=36), nullable=True),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("computed_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["research_experiments.experiment_id"],
            name=op.f("fk_metric_sets_experiment_id_research_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["fold_id"],
            ["research_folds.fold_id"],
            name=op.f("fk_metric_sets_fold_id_research_folds"),
        ),
        sa.PrimaryKeyConstraint("metric_set_id", name=op.f("pk_metric_sets")),
    )
    with op.batch_alter_table("metric_sets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_metric_sets_experiment_id"), ["experiment_id"], unique=False
        )

    op.create_table(
        "research_predictions",
        sa.Column("research_prediction_id", sa.String(length=36), nullable=False),
        sa.Column("experiment_id", sa.String(length=36), nullable=False),
        sa.Column("fold_id", sa.String(length=36), nullable=True),
        sa.Column("model_id", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("generated_at", UTCDateTime(), nullable=False),
        sa.Column("decision_at", UTCDateTime(), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("feature_snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("expected_excess_return", sa.Float(), nullable=True),
        sa.Column("probability", sa.Float(), nullable=True),
        sa.Column("uncertainty", sa.JSON(), nullable=False),
        sa.Column("calibration_version", sa.String(length=80), nullable=True),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "decision_at <= generated_at",
            name=op.f("ck_research_predictions_decision_before_generation"),
        ),
        sa.ForeignKeyConstraint(
            ["experiment_id"],
            ["research_experiments.experiment_id"],
            name=op.f("fk_research_predictions_experiment_id_research_experiments"),
        ),
        sa.ForeignKeyConstraint(
            ["feature_snapshot_id"],
            ["feature_snapshots.snapshot_id"],
            name=op.f("fk_research_predictions_feature_snapshot_id_feature_snapshots"),
        ),
        sa.ForeignKeyConstraint(
            ["fold_id"],
            ["research_folds.fold_id"],
            name=op.f("fk_research_predictions_fold_id_research_folds"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_research_predictions_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("research_prediction_id", name=op.f("pk_research_predictions")),
    )
    with op.batch_alter_table("research_predictions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_predictions_experiment_id"), ["experiment_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("research_predictions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_predictions_experiment_id"))

    op.drop_table("research_predictions")
    with op.batch_alter_table("metric_sets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_metric_sets_experiment_id"))

    op.drop_table("metric_sets")
    with op.batch_alter_table("research_folds", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_folds_experiment_id"))

    op.drop_table("research_folds")
    op.drop_table("champion_challenger_comparisons")
    op.drop_table("research_experiments")
    with op.batch_alter_table("realized_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_realized_outcomes_security_id"))

    op.drop_table("realized_outcomes")
    op.drop_table("dataset_versions")
    op.drop_table("model_configs")
    op.drop_table("label_definitions")
    op.drop_table("feature_set_versions")
    # ### end Alembic commands ###
