"""sp500 anchor graph

Revision ID: 0013
Revises: 0012
Create Date: 2026-10-03 15:04:06.096187
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0013"
down_revision = "0012"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = (
    "sp500_anchors",
    "sp500_anchor_members",
    "sp500_anchor_crosschecks",
    "sp500_membership_segments",
    "security_ticker_alias",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sp500_anchors",
        sa.Column("anchor_id", sa.String(length=36), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("source_type", sa.String(length=30), nullable=False),
        sa.Column("evidence_kind", sa.String(length=50), nullable=False),
        sa.Column("evidence_tier", sa.String(length=40), nullable=False),
        sa.Column("form", sa.String(length=12), nullable=False),
        sa.Column("accession", sa.String(length=20), nullable=False),
        sa.Column("filer_cik", sa.String(length=10), nullable=False),
        sa.Column("source_available_at", UTCDateTime(), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("resolved_count", sa.Integer(), nullable=False),
        sa.Column("unresolved_count", sa.Integer(), nullable=False),
        sa.Column("excluded_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("notes", sa.JSON(), nullable=False),
        sa.Column("parser_version", sa.String(length=50), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "source_available_at >= as_of_date",
            name=op.f("ck_sp500_anchors_available_after_period"),
        ),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_sp500_anchors_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("anchor_id", name=op.f("pk_sp500_anchors")),
        sa.UniqueConstraint("accession", "parser_version", name="uq_sp500_anchor_accession"),
    )
    with op.batch_alter_table("sp500_anchors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sp500_anchors_as_of_date"), ["as_of_date"], unique=False
        )

    op.create_table(
        "security_ticker_alias",
        sa.Column("alias_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=True),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("bounds", sa.String(length=10), nullable=False),
        sa.Column("source", sa.String(length=60), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("confidence", sa.String(length=12), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "bounds IN ('EXACT','PARTIAL')", name=op.f("ck_security_ticker_alias_bounds_values")
        ),
        sa.CheckConstraint(
            "valid_to IS NULL OR valid_from IS NULL OR valid_to >= valid_from",
            name=op.f("ck_security_ticker_alias_alias_order"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_security_ticker_alias_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("alias_id", name=op.f("pk_security_ticker_alias")),
    )
    with op.batch_alter_table("security_ticker_alias", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_security_ticker_alias_security_id"), ["security_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_security_ticker_alias_ticker"), ["ticker"], unique=False
        )

    op.create_table(
        "sp500_anchor_crosschecks",
        sa.Column("check_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_a_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_b_id", sa.String(length=36), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["anchor_a_id"],
            ["sp500_anchors.anchor_id"],
            name=op.f("fk_sp500_anchor_crosschecks_anchor_a_id_sp500_anchors"),
        ),
        sa.ForeignKeyConstraint(
            ["anchor_b_id"],
            ["sp500_anchors.anchor_id"],
            name=op.f("fk_sp500_anchor_crosschecks_anchor_b_id_sp500_anchors"),
        ),
        sa.PrimaryKeyConstraint("check_id", name=op.f("pk_sp500_anchor_crosschecks")),
    )
    op.create_table(
        "sp500_anchor_members",
        sa.Column("member_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=True),
        sa.Column("cusip", sa.String(length=9), nullable=True),
        sa.Column("isin", sa.String(length=12), nullable=True),
        sa.Column("ticker_as_reported", sa.String(length=20), nullable=True),
        sa.Column("issuer_name", sa.String(length=300), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=True),
        sa.Column("lei", sa.String(length=20), nullable=True),
        sa.Column("source_position", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Float(), nullable=True),
        sa.Column("value_usd", sa.Float(), nullable=True),
        sa.Column("pct_net_assets", sa.Float(), nullable=True),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("identity_basis", sa.String(length=30), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.CheckConstraint(
            "classification IN ('INDEX_EQUITY_CANDIDATE','NON_EQUITY','TRANSIENT_CORPORATE_ACTION','UNRESOLVED')",
            name=op.f("ck_sp500_anchor_members_classification_values"),
        ),
        sa.ForeignKeyConstraint(
            ["anchor_id"],
            ["sp500_anchors.anchor_id"],
            name=op.f("fk_sp500_anchor_members_anchor_id_sp500_anchors"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_sp500_anchor_members_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("member_id", name=op.f("pk_sp500_anchor_members")),
    )
    with op.batch_alter_table("sp500_anchor_members", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sp500_anchor_members_anchor_id"), ["anchor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sp500_anchor_members_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "sp500_membership_segments",
        sa.Column("segment_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_a_id", sa.String(length=36), nullable=False),
        sa.Column("anchor_b_id", sa.String(length=36), nullable=False),
        sa.Column("run_id", sa.String(length=36), nullable=True),
        sa.Column("engine_version", sa.String(length=40), nullable=False),
        sa.Column("n_confirmed_events", sa.Integer(), nullable=False),
        sa.Column("n_delta_added", sa.Integer(), nullable=False),
        sa.Column("n_delta_removed", sa.Integer(), nullable=False),
        sa.Column("forward_ok", sa.Boolean(), nullable=False),
        sa.Column("backward_ok", sa.Boolean(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("deltas", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "status IN ('VALIDATED','LOCAL_GAPS','IDENTITY_UNRESOLVED')",
            name=op.f("ck_sp500_membership_segments_status_values"),
        ),
        sa.ForeignKeyConstraint(
            ["anchor_a_id"],
            ["sp500_anchors.anchor_id"],
            name=op.f("fk_sp500_membership_segments_anchor_a_id_sp500_anchors"),
        ),
        sa.ForeignKeyConstraint(
            ["anchor_b_id"],
            ["sp500_anchors.anchor_id"],
            name=op.f("fk_sp500_membership_segments_anchor_b_id_sp500_anchors"),
        ),
        sa.PrimaryKeyConstraint("segment_id", name=op.f("pk_sp500_membership_segments")),
    )
    with op.batch_alter_table("sp500_membership_segments", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sp500_membership_segments_anchor_a_id"), ["anchor_a_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_sp500_membership_segments_anchor_b_id"), ["anchor_b_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sp500_membership_segments", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sp500_membership_segments_anchor_b_id"))
        batch_op.drop_index(batch_op.f("ix_sp500_membership_segments_anchor_a_id"))

    op.drop_table("sp500_membership_segments")
    with op.batch_alter_table("sp500_anchor_members", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sp500_anchor_members_security_id"))
        batch_op.drop_index(batch_op.f("ix_sp500_anchor_members_anchor_id"))

    op.drop_table("sp500_anchor_members")
    op.drop_table("sp500_anchor_crosschecks")
    with op.batch_alter_table("security_ticker_alias", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_security_ticker_alias_ticker"))
        batch_op.drop_index(batch_op.f("ix_security_ticker_alias_security_id"))

    op.drop_table("security_ticker_alias")
    with op.batch_alter_table("sp500_anchors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sp500_anchors_as_of_date"))

    op.drop_table("sp500_anchors")
    # ### end Alembic commands ###
