"""13f list and security succession

Revision ID: 0014
Revises: 0013
Create Date: 2026-10-03 15:55:46.785397
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0014"
down_revision = "0013"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("sec_13f_list_entries", "security_succession")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sec_13f_list_entries",
        sa.Column("entry_id", sa.String(length=36), nullable=False),
        sa.Column("quarter", sa.String(length=6), nullable=False),
        sa.Column("cusip", sa.String(length=9), nullable=False),
        sa.Column("issuer_name", sa.String(length=200), nullable=False),
        sa.Column("issuer_description", sa.String(length=100), nullable=False),
        sa.Column("status_added_deleted", sa.String(length=10), nullable=True),
        sa.Column("raw_source_hash", sa.String(length=64), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("parser_version", sa.String(length=40), nullable=False),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_sec_13f_list_entries_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("entry_id", name=op.f("pk_sec_13f_list_entries")),
    )
    with op.batch_alter_table("sec_13f_list_entries", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sec_13f_list_entries_cusip"), ["cusip"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_sec_13f_list_entries_quarter"), ["quarter"], unique=False
        )

    op.create_table(
        "security_succession",
        sa.Column("succession_id", sa.String(length=36), nullable=False),
        sa.Column("security_predecessor_id", sa.String(length=36), nullable=False),
        sa.Column("security_successor_id", sa.String(length=36), nullable=False),
        sa.Column("effective_at", UTCDateTime(), nullable=True),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("exchange_ratio", sa.Float(), nullable=True),
        sa.Column("membership_continuity", sa.Boolean(), nullable=False),
        sa.Column("source", sa.String(length=80), nullable=False),
        sa.Column("source_hash", sa.String(length=64), nullable=True),
        sa.Column("note", sa.String(length=400), nullable=True),
        sa.Column("ingested_at", UTCDateTime(), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('NAME_CHANGE_SAME_SECURITY','TICKER_CHANGE_SAME_SECURITY','SECURITY_REPLACEMENT_SUCCESSOR','SHARE_CLASS_CHANGE','TRUE_INDEX_EXIT','TRUE_INDEX_ENTRY','SAME_SECURITY_IDENTITY_LINK')",
            name=op.f("ck_security_succession_event_type_values"),
        ),
        sa.CheckConstraint(
            "security_predecessor_id != security_successor_id",
            name=op.f("ck_security_succession_distinct_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["security_predecessor_id"],
            ["securities.security_id"],
            name=op.f("fk_security_succession_security_predecessor_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["security_successor_id"],
            ["securities.security_id"],
            name=op.f("fk_security_succession_security_successor_id_securities"),
        ),
        sa.PrimaryKeyConstraint("succession_id", name=op.f("pk_security_succession")),
    )
    with op.batch_alter_table("security_succession", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_security_succession_security_predecessor_id"),
            ["security_predecessor_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_security_succession_security_successor_id"),
            ["security_successor_id"],
            unique=False,
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("security_succession", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_security_succession_security_successor_id"))
        batch_op.drop_index(batch_op.f("ix_security_succession_security_predecessor_id"))

    op.drop_table("security_succession")
    with op.batch_alter_table("sec_13f_list_entries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sec_13f_list_entries_quarter"))
        batch_op.drop_index(batch_op.f("ix_sec_13f_list_entries_cusip"))

    op.drop_table("sec_13f_list_entries")
    # ### end Alembic commands ###
