"""simulation lab

Revision ID: 0016
Revises: 0015
Create Date: 2026-10-03 16:44:07.063412
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "0016"
down_revision = "0015"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = (
    "simulations",
    "simulation_observations",
    "simulation_outcomes",
    "simulation_postmortems",
    "research_hypotheses",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_hypotheses",
        sa.Column("hypothesis_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("statement", sa.String(length=1000), nullable=False),
        sa.Column("evidence", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_by", sa.String(length=60), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("hypothesis_id", name=op.f("pk_research_hypotheses")),
    )
    op.create_table(
        "simulations",
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=10), nullable=False),
        sa.Column("decision_at", UTCDateTime(), nullable=False),
        sa.Column("analyzer_version", sa.String(length=60), nullable=False),
        sa.Column("feature_version", sa.String(length=40), nullable=False),
        sa.Column("model_id", sa.String(length=64), nullable=True),
        sa.Column("model_version", sa.String(length=64), nullable=True),
        sa.Column("rules_version", sa.String(length=40), nullable=False),
        sa.Column("prediction_status", sa.String(length=30), nullable=False),
        sa.Column("price_snapshot", sa.JSON(), nullable=False),
        sa.Column("fundamental_snapshot", sa.JSON(), nullable=False),
        sa.Column("technical_snapshot", sa.JSON(), nullable=False),
        sa.Column("valuation_snapshot", sa.JSON(), nullable=False),
        sa.Column("support_resistance_snapshot", sa.JSON(), nullable=False),
        sa.Column("trade_plan_snapshot", sa.JSON(), nullable=False),
        sa.Column("market_regime_snapshot", sa.JSON(), nullable=False),
        sa.Column("data_quality", sa.JSON(), nullable=False),
        sa.Column("funding_snapshot", sa.JSON(), nullable=True),
        sa.Column("open_interest_snapshot", sa.JSON(), nullable=True),
        sa.Column("basis_snapshot", sa.JSON(), nullable=True),
        sa.Column("onchain_snapshot", sa.JSON(), nullable=True),
        sa.Column("plan_origin", sa.String(length=14), nullable=False),
        sa.Column("original_pitquant_plan", sa.JSON(), nullable=True),
        sa.Column("final_simulated_plan", sa.JSON(), nullable=False),
        sa.Column("side", sa.String(length=5), nullable=False),
        sa.Column("entry_type", sa.String(length=12), nullable=False),
        sa.Column("entry_zone_low", sa.Float(), nullable=False),
        sa.Column("entry_zone_high", sa.Float(), nullable=False),
        sa.Column("entry_price_actual", sa.Float(), nullable=True),
        sa.Column("stop_loss", sa.Float(), nullable=False),
        sa.Column("invalidation_level", sa.Float(), nullable=True),
        sa.Column("target_1", sa.Float(), nullable=False),
        sa.Column("target_2", sa.Float(), nullable=True),
        sa.Column("target_3_optional", sa.Float(), nullable=True),
        sa.Column("risk_reward_expected", sa.Float(), nullable=True),
        sa.Column("position_size_simulated", sa.Float(), nullable=False),
        sa.Column("capital_at_risk", sa.Float(), nullable=False),
        sa.Column("time_horizon_sessions", sa.Integer(), nullable=False),
        sa.Column("expiration_at", UTCDateTime(), nullable=False),
        sa.Column("benchmark_security_id", sa.String(length=36), nullable=True),
        sa.CheckConstraint(
            "asset_type IN ('EQUITY','BTC')", name=op.f("ck_simulations_asset_type_values")
        ),
        sa.CheckConstraint(
            "mode IN ('MANUAL_SIMULATION','AUTO_PAPER')", name=op.f("ck_simulations_mode_values")
        ),
        sa.CheckConstraint(
            "plan_origin IN ('PITQUANT','USER_MODIFIED','USER_DEFINED')",
            name=op.f("ck_simulations_plan_origin_values"),
        ),
        sa.CheckConstraint(
            "created_at >= decision_at", name=op.f("ck_simulations_created_after_decision")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_simulations_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("simulation_id", name=op.f("pk_simulations")),
    )
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulations_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "simulation_observations",
        sa.Column("observation_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("observed_at", UTCDateTime(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.simulation_id"],
            name=op.f("fk_simulation_observations_simulation_id_simulations"),
        ),
        sa.PrimaryKeyConstraint("observation_id", name=op.f("pk_simulation_observations")),
    )
    with op.batch_alter_table("simulation_observations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulation_observations_simulation_id"), ["simulation_id"], unique=False
        )

    op.create_table(
        "simulation_outcomes",
        sa.Column("outcome_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("evaluated_at", UTCDateTime(), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("is_closed", sa.Boolean(), nullable=False),
        sa.Column("entry_date", sa.Date(), nullable=True),
        sa.Column("entry_price", sa.Float(), nullable=True),
        sa.Column("exit_date", sa.Date(), nullable=True),
        sa.Column("realized_return", sa.Float(), nullable=True),
        sa.Column("excess_return_vs_benchmark", sa.Float(), nullable=True),
        sa.Column("realized_r", sa.Float(), nullable=True),
        sa.Column("mfe", sa.Float(), nullable=True),
        sa.Column("mae", sa.Float(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("days_to_entry", sa.Integer(), nullable=True),
        sa.Column("days_to_stop", sa.Integer(), nullable=True),
        sa.Column("days_to_tp1", sa.Integer(), nullable=True),
        sa.Column("days_to_tp2", sa.Integer(), nullable=True),
        sa.Column("holding_period", sa.Integer(), nullable=True),
        sa.Column("prediction_direction_correct", sa.Boolean(), nullable=True),
        sa.Column("trade_plan_execution_correct", sa.Boolean(), nullable=True),
        sa.Column("timeline", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.simulation_id"],
            name=op.f("fk_simulation_outcomes_simulation_id_simulations"),
        ),
        sa.PrimaryKeyConstraint("outcome_id", name=op.f("pk_simulation_outcomes")),
    )
    with op.batch_alter_table("simulation_outcomes", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulation_outcomes_simulation_id"), ["simulation_id"], unique=False
        )

    op.create_table(
        "simulation_postmortems",
        sa.Column("postmortem_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("primary_cause", sa.String(length=40), nullable=False),
        sa.Column("secondary_causes", sa.JSON(), nullable=False),
        sa.Column("notes", sa.String(length=2000), nullable=True),
        sa.Column("classified_by", sa.String(length=60), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("created_at", UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.simulation_id"],
            name=op.f("fk_simulation_postmortems_simulation_id_simulations"),
        ),
        sa.PrimaryKeyConstraint("postmortem_id", name=op.f("pk_simulation_postmortems")),
    )
    with op.batch_alter_table("simulation_postmortems", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulation_postmortems_simulation_id"), ["simulation_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} "
                f"FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("simulation_postmortems", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulation_postmortems_simulation_id"))

    op.drop_table("simulation_postmortems")
    with op.batch_alter_table("simulation_outcomes", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulation_outcomes_simulation_id"))

    op.drop_table("simulation_outcomes")
    with op.batch_alter_table("simulation_observations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulation_observations_simulation_id"))

    op.drop_table("simulation_observations")
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulations_security_id"))

    op.drop_table("simulations")
    op.drop_table("research_hypotheses")
    # ### end Alembic commands ###
