"""simulation events counterfactuals

Revision ID: 0018
Revises: 0017
Create Date: 2026-10-03 21:07:57.439604
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import pitquant.db.base

revision = "0018"
down_revision = "0017"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("simulation_events", "simulation_counterfactuals")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "simulation_counterfactuals",
        sa.Column("counterfactual_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("evaluated_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("plan_label", sa.String(length=40), nullable=False),
        sa.Column("last_bar", sa.Date(), nullable=True),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("plan", sa.JSON(), nullable=False),
        sa.Column("metrics", sa.JSON(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("timeline", sa.JSON(), nullable=False),
        sa.Column("label", sa.String(length=20), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.simulation_id"],
            name=op.f("fk_simulation_counterfactuals_simulation_id_simulations"),
        ),
        sa.PrimaryKeyConstraint("counterfactual_id", name=op.f("pk_simulation_counterfactuals")),
    )
    with op.batch_alter_table("simulation_counterfactuals", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulation_counterfactuals_simulation_id"),
            ["simulation_id"],
            unique=False,
        )

    op.create_table(
        "simulation_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("simulation_id", sa.String(length=36), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=30), nullable=False),
        sa.Column("occurred_at", sa.Date(), nullable=False),
        sa.Column("source_bar_timestamp", sa.Date(), nullable=True),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("engine_version", sa.String(length=30), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["simulation_id"],
            ["simulations.simulation_id"],
            name=op.f("fk_simulation_events_simulation_id_simulations"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_simulation_events")),
        sa.UniqueConstraint("simulation_id", "sequence_number", name="uq_simulation_event_seq"),
    )
    with op.batch_alter_table("simulation_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_simulation_events_simulation_id"), ["simulation_id"], unique=False
        )

    with op.batch_alter_table("simulation_outcomes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("prediction_outcome", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("execution_outcome", sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column("event_count", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("engine_version", sa.String(length=30), nullable=True))

    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.alter_column(
            "entry_type",
            existing_type=sa.String(length=12),
            type_=sa.String(length=20),
            existing_nullable=False,
        )
        batch_op.add_column(sa.Column("snapshot_hash", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("source_provenance", sa.JSON(), nullable=True))

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.drop_column("source_provenance")
        batch_op.alter_column(
            "entry_type",
            existing_type=sa.String(length=20),
            type_=sa.String(length=12),
            existing_nullable=False,
        )
        batch_op.drop_column("snapshot_hash")

    with op.batch_alter_table("simulation_outcomes", schema=None) as batch_op:
        batch_op.drop_column("engine_version")
        batch_op.drop_column("event_count")
        batch_op.drop_column("execution_outcome")
        batch_op.drop_column("prediction_outcome")

    with op.batch_alter_table("simulation_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulation_events_simulation_id"))

    op.drop_table("simulation_events")
    with op.batch_alter_table("simulation_counterfactuals", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_simulation_counterfactuals_simulation_id"))

    op.drop_table("simulation_counterfactuals")
    # ### end Alembic commands ###
