"""simulation engine pinning and historical observations

Revision ID: 0019
Revises: 0018
Create Date: 2026-10-03 22:06:41.523097
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0019"
down_revision = "0018"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("simulation_counterfactuals", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "simulation_engine_version",
                sa.String(length=20),
                server_default="v1",
                nullable=False,
            )
        )

    with op.batch_alter_table("simulation_events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("event_schema_version", sa.Integer(), server_default="1", nullable=False)
        )

    with op.batch_alter_table("simulation_observations", schema=None) as batch_op:
        batch_op.add_column(sa.Column("horizon_label", sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column("source_bar_date", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("observation_schema_version", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("analyzer_version", sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column("feature_version", sa.String(length=40), nullable=True))
        batch_op.create_unique_constraint(
            "uq_simulation_observation_label", ["simulation_id", "horizon_label"]
        )

    with op.batch_alter_table("simulation_outcomes", schema=None) as batch_op:
        batch_op.add_column(sa.Column("bars_to_entry", sa.Integer(), nullable=True))

    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "simulation_engine_version",
                sa.String(length=20),
                server_default="v1",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("simulations", schema=None) as batch_op:
        batch_op.drop_column("simulation_engine_version")

    with op.batch_alter_table("simulation_outcomes", schema=None) as batch_op:
        batch_op.drop_column("bars_to_entry")

    with op.batch_alter_table("simulation_observations", schema=None) as batch_op:
        batch_op.drop_constraint("uq_simulation_observation_label", type_="unique")
        batch_op.drop_column("feature_version")
        batch_op.drop_column("analyzer_version")
        batch_op.drop_column("observation_schema_version")
        batch_op.drop_column("source_bar_date")
        batch_op.drop_column("horizon_label")

    with op.batch_alter_table("simulation_events", schema=None) as batch_op:
        batch_op.drop_column("event_schema_version")

    with op.batch_alter_table("simulation_counterfactuals", schema=None) as batch_op:
        batch_op.drop_column("simulation_engine_version")

    # ### end Alembic commands ###
