"""paper positions and reviews

Revision ID: 0022
Revises: 0021
Create Date: 2026-10-04 14:28:38.481860
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import pitquant.db.base

revision = "0022"
down_revision = "0021"
branch_labels = None
depends_on = None


ADDED_IMMUTABLE_TABLES = ("paper_positions", "paper_position_events", "position_reviews")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "paper_positions",
        sa.Column("position_id", sa.String(length=36), nullable=False),
        sa.Column("asset_type", sa.String(length=10), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("target_return", sa.Float(), nullable=True),
        sa.Column("stop_price", sa.Float(), nullable=True),
        sa.Column("stop_rule", sa.String(length=40), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=False),
        sa.Column("is_synthetic", sa.Boolean(), nullable=False),
        sa.Column("opened_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "asset_type IN ('EQUITY','BTC')", name=op.f("ck_paper_positions_asset_values")
        ),
        sa.CheckConstraint(
            "horizon_months BETWEEN 1 AND 60", name=op.f("ck_paper_positions_horizon_range")
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_paper_positions_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("position_id", name=op.f("pk_paper_positions")),
    )
    with op.batch_alter_table("paper_positions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_paper_positions_asset_type"), ["asset_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_paper_positions_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "paper_position_events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("position_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=10), nullable=False),
        sa.Column("occurred_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price_source", sa.String(length=40), nullable=False),
        sa.Column("price_freshness", sa.String(length=20), nullable=True),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "event_type IN ('OPEN','ADD','REDUCE','CLOSE')",
            name=op.f("ck_paper_position_events_event_values"),
        ),
        sa.CheckConstraint(
            "price > 0 AND quantity > 0",
            name=op.f("ck_paper_position_events_positive_price_quantity"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["paper_positions.position_id"],
            name=op.f("fk_paper_position_events_position_id_paper_positions"),
        ),
        sa.PrimaryKeyConstraint("event_id", name=op.f("pk_paper_position_events")),
    )
    with op.batch_alter_table("paper_position_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_paper_position_events_position_id"), ["position_id"], unique=False
        )

    op.create_table(
        "position_reviews",
        sa.Column("review_id", sa.String(length=36), nullable=False),
        sa.Column("position_id", sa.String(length=36), nullable=False),
        sa.Column("reviewed_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("engine_version", sa.String(length=30), nullable=False),
        sa.Column("horizon_bucket", sa.String(length=10), nullable=False),
        sa.Column("recommendation", sa.String(length=6), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("avg_cost", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("pnl_pct", sa.Float(), nullable=False),
        sa.Column("rules", sa.JSON(), nullable=False),
        sa.Column("inputs", sa.JSON(), nullable=False),
        sa.Column("context_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "recommendation IN ('ADD','HOLD','SELL')",
            name=op.f("ck_position_reviews_recommendation_values"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["paper_positions.position_id"],
            name=op.f("fk_position_reviews_position_id_paper_positions"),
        ),
        sa.PrimaryKeyConstraint("review_id", name=op.f("pk_position_reviews")),
    )
    with op.batch_alter_table("position_reviews", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_position_reviews_position_id"), ["position_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("position_reviews", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_position_reviews_position_id"))

    op.drop_table("position_reviews")
    with op.batch_alter_table("paper_position_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_position_events_position_id"))

    op.drop_table("paper_position_events")
    with op.batch_alter_table("paper_positions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_paper_positions_security_id"))
        batch_op.drop_index(batch_op.f("ix_paper_positions_asset_type"))

    op.drop_table("paper_positions")
    # ### end Alembic commands ###
