"""daily routine picks and evaluations

Revision ID: 0023
Revises: 0022
Create Date: 2026-10-04 14:51:57.652805
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import pitquant.db.base

revision = "0023"
down_revision = "0022"
branch_labels = None
depends_on = None


ADDED_IMMUTABLE_TABLES = ("daily_picks", "daily_evaluations")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_picks",
        sa.Column("pick_id", sa.String(length=36), nullable=False),
        sa.Column("run_date", sa.Date(), nullable=False),
        sa.Column("market", sa.String(length=12), nullable=False),
        sa.Column("ticker", sa.String(length=20), nullable=True),
        sa.Column("security_id", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("params_version", sa.String(length=30), nullable=False),
        sa.Column("params", sa.JSON(), nullable=False),
        sa.Column("price", sa.Float(), nullable=True),
        sa.Column("price_freshness", sa.String(length=20), nullable=True),
        sa.Column("decisions", sa.JSON(), nullable=False),
        sa.Column("unavailable", sa.JSON(), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "market IN ('IBEX','SP500','MSCI_WORLD','BTC')",
            name=op.f("ck_daily_picks_market_values"),
        ),
        sa.CheckConstraint(
            "status IN ('ANALYZED','NO_DATA')", name=op.f("ck_daily_picks_status_values")
        ),
        sa.PrimaryKeyConstraint("pick_id", name=op.f("pk_daily_picks")),
        sa.UniqueConstraint("run_date", "market", name="uq_daily_pick_day_market"),
    )
    with op.batch_alter_table("daily_picks", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_daily_picks_run_date"), ["run_date"], unique=False)

    op.create_table(
        "daily_evaluations",
        sa.Column("evaluation_id", sa.String(length=36), nullable=False),
        sa.Column("position_id", sa.String(length=36), nullable=False),
        sa.Column("week_key", sa.String(length=12), nullable=False),
        sa.Column("evaluated_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.Column("target_progress", sa.Float(), nullable=True),
        sa.Column("max_favorable", sa.Float(), nullable=True),
        sa.Column("max_adverse", sa.Float(), nullable=True),
        sa.Column("outcome_date", sa.Date(), nullable=True),
        sa.Column("bars_used", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('IN_PROGRESS','TARGET_HIT','STOP_HIT','AMBIGUOUS_STOP','EXPIRED')",
            name=op.f("ck_daily_evaluations_state_values"),
        ),
        sa.ForeignKeyConstraint(
            ["position_id"],
            ["paper_positions.position_id"],
            name=op.f("fk_daily_evaluations_position_id_paper_positions"),
        ),
        sa.PrimaryKeyConstraint("evaluation_id", name=op.f("pk_daily_evaluations")),
        sa.UniqueConstraint("position_id", "week_key", name="uq_daily_eval_position_week"),
    )
    with op.batch_alter_table("daily_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_evaluations_position_id"), ["position_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_evaluations_position_id"))

    op.drop_table("daily_evaluations")
    with op.batch_alter_table("daily_picks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_picks_run_date"))

    op.drop_table("daily_picks")
    # ### end Alembic commands ###
