"""daily virtual evaluations

Revision ID: 0024
Revises: 0023
Create Date: 2026-10-04 15:11:01.077063
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import pitquant.db.base

revision = "0024"
down_revision = "0023"
branch_labels = None
depends_on = None


ADDED_IMMUTABLE_TABLES = ("daily_virtual_evaluations",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_virtual_evaluations",
        sa.Column("virtual_id", sa.String(length=36), nullable=False),
        sa.Column("pick_id", sa.String(length=36), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("week_key", sa.String(length=12), nullable=False),
        sa.Column("evaluated_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("return_pct", sa.Float(), nullable=False),
        sa.Column("target_progress", sa.Float(), nullable=True),
        sa.Column("max_favorable", sa.Float(), nullable=True),
        sa.Column("max_adverse", sa.Float(), nullable=True),
        sa.Column("outcome_date", sa.Date(), nullable=True),
        sa.Column("bars_used", sa.Integer(), nullable=False),
        sa.Column("detail", sa.JSON(), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "state IN ('IN_PROGRESS','TARGET_HIT','STOP_HIT','AMBIGUOUS_STOP','EXPIRED')",
            name=op.f("ck_daily_virtual_evaluations_state_values"),
        ),
        sa.ForeignKeyConstraint(
            ["pick_id"],
            ["daily_picks.pick_id"],
            name=op.f("fk_daily_virtual_evaluations_pick_id_daily_picks"),
        ),
        sa.PrimaryKeyConstraint("virtual_id", name=op.f("pk_daily_virtual_evaluations")),
        sa.UniqueConstraint(
            "pick_id", "horizon_months", "week_key", name="uq_daily_virtual_pick_h_week"
        ),
    )
    with op.batch_alter_table("daily_virtual_evaluations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_daily_virtual_evaluations_pick_id"), ["pick_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("daily_virtual_evaluations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_daily_virtual_evaluations_pick_id"))

    op.drop_table("daily_virtual_evaluations")
    # ### end Alembic commands ###
