"""research feature snapshots targets and filing analysis

Revision ID: 0026
Revises: 0025
Create Date: 2026-10-04 19:30:58.205958
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import pitquant.db.base

revision = "0026"
down_revision = "0025"
branch_labels = None
depends_on = None


ADDED_IMMUTABLE_TABLES = (
    "research_feature_snapshots",
    "research_targets",
    "filing_analysis_snapshots",
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "research_feature_snapshots",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("decision_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("decision_session", sa.Date(), nullable=False),
        sa.Column("exchange", sa.String(length=8), nullable=False),
        sa.Column("feature_set_version", sa.String(length=30), nullable=False),
        sa.Column("cohort_definition", sa.String(length=60), nullable=False),
        sa.Column("cohort_size", sa.Integer(), nullable=False),
        sa.Column("features", sa.JSON(), nullable=False),
        sa.Column("ranks", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.Column("feature_hash", sa.String(length=64), nullable=False),
        sa.Column("code_commit", sa.String(length=40), nullable=True),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_research_feature_snapshots_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_research_feature_snapshots")),
        sa.UniqueConstraint(
            "security_id", "decision_at", "feature_set_version", name="uq_research_feature_snapshot"
        ),
    )
    with op.batch_alter_table("research_feature_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_feature_snapshots_decision_at"), ["decision_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_feature_snapshots_decision_session"),
            ["decision_session"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_research_feature_snapshots_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "research_targets",
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("decision_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("horizon_months", sa.Integer(), nullable=False),
        sa.Column("target_set_version", sa.String(length=30), nullable=False),
        sa.Column("benchmark_id", sa.String(length=36), nullable=True),
        sa.Column("benchmark_ticker", sa.String(length=20), nullable=True),
        sa.Column("benchmark_type", sa.String(length=40), nullable=True),
        sa.Column("benchmark_source", sa.String(length=60), nullable=True),
        sa.Column("entry_session", sa.Date(), nullable=True),
        sa.Column("exit_session", sa.Date(), nullable=True),
        sa.Column(
            "label_available_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("status", sa.String(length=12), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("security_total_return", sa.Float(), nullable=True),
        sa.Column("benchmark_total_return", sa.Float(), nullable=True),
        sa.Column("excess_total_return", sa.Float(), nullable=True),
        sa.Column("outperform", sa.Boolean(), nullable=True),
        sa.Column("direction_up", sa.Boolean(), nullable=True),
        sa.Column("max_drawdown", sa.Float(), nullable=True),
        sa.Column("drawdown_10", sa.Boolean(), nullable=True),
        sa.Column("drawdown_15", sa.Boolean(), nullable=True),
        sa.Column("drawdown_20", sa.Boolean(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('OK','UNAVAILABLE')", name=op.f("ck_research_targets_status_values")
        ),
        sa.ForeignKeyConstraint(
            ["benchmark_id"],
            ["securities.security_id"],
            name=op.f("fk_research_targets_benchmark_id_securities"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_research_targets_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("target_id", name=op.f("pk_research_targets")),
        sa.UniqueConstraint(
            "security_id",
            "decision_at",
            "horizon_months",
            "target_set_version",
            name="uq_research_target",
        ),
    )
    with op.batch_alter_table("research_targets", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_research_targets_decision_at"), ["decision_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_research_targets_security_id"), ["security_id"], unique=False
        )

    op.create_table(
        "filing_analysis_snapshots",
        sa.Column("analysis_id", sa.String(length=36), nullable=False),
        sa.Column("accession_number", sa.String(length=25), nullable=False),
        sa.Column("security_id", sa.String(length=36), nullable=False),
        sa.Column("issuer_id", sa.String(length=36), nullable=True),
        sa.Column("form", sa.String(length=20), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("accepted_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column(
            "filing_available_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("document_hash", sa.String(length=64), nullable=False),
        sa.Column("analysis_schema_version", sa.String(length=30), nullable=False),
        sa.Column("prompt_version", sa.String(length=30), nullable=False),
        sa.Column("model_provider", sa.String(length=40), nullable=False),
        sa.Column("model_name", sa.String(length=80), nullable=False),
        sa.Column("model_version", sa.String(length=80), nullable=False),
        sa.Column("analysis", sa.JSON(), nullable=False),
        sa.Column("analysis_hash", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=10), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("warnings", sa.JSON(), nullable=False),
        sa.Column(
            "analysis_available_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False
        ),
        sa.Column("is_retrospective", sa.Boolean(), nullable=False),
        sa.Column("created_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "status IN ('COMPLETE','PARTIAL','FAILED')",
            name=op.f("ck_filing_analysis_snapshots_status_values"),
        ),
        sa.CheckConstraint(
            "analysis_available_at >= filing_available_at OR is_retrospective",
            name=op.f("ck_filing_analysis_snapshots_analysis_not_before_filing"),
        ),
        sa.ForeignKeyConstraint(
            ["accession_number"],
            ["sec_filings.accession_number"],
            name=op.f("fk_filing_analysis_snapshots_accession_number_sec_filings"),
        ),
        sa.ForeignKeyConstraint(
            ["issuer_id"],
            ["issuers.issuer_id"],
            name=op.f("fk_filing_analysis_snapshots_issuer_id_issuers"),
        ),
        sa.ForeignKeyConstraint(
            ["security_id"],
            ["securities.security_id"],
            name=op.f("fk_filing_analysis_snapshots_security_id_securities"),
        ),
        sa.PrimaryKeyConstraint("analysis_id", name=op.f("pk_filing_analysis_snapshots")),
        sa.UniqueConstraint(
            "accession_number",
            "analysis_schema_version",
            "prompt_version",
            "model_name",
            "model_version",
            "document_hash",
            name="uq_filing_analysis_version",
        ),
    )
    with op.batch_alter_table("filing_analysis_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_filing_analysis_snapshots_accession_number"),
            ["accession_number"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filing_analysis_snapshots_analysis_available_at"),
            ["analysis_available_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filing_analysis_snapshots_filing_available_at"),
            ["filing_available_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_filing_analysis_snapshots_security_id"), ["security_id"], unique=False
        )

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("filing_analysis_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_filing_analysis_snapshots_security_id"))
        batch_op.drop_index(batch_op.f("ix_filing_analysis_snapshots_filing_available_at"))
        batch_op.drop_index(batch_op.f("ix_filing_analysis_snapshots_analysis_available_at"))
        batch_op.drop_index(batch_op.f("ix_filing_analysis_snapshots_accession_number"))

    op.drop_table("filing_analysis_snapshots")
    with op.batch_alter_table("research_targets", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_targets_security_id"))
        batch_op.drop_index(batch_op.f("ix_research_targets_decision_at"))

    op.drop_table("research_targets")
    with op.batch_alter_table("research_feature_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_research_feature_snapshots_security_id"))
        batch_op.drop_index(batch_op.f("ix_research_feature_snapshots_decision_session"))
        batch_op.drop_index(batch_op.f("ix_research_feature_snapshots_decision_at"))

    op.drop_table("research_feature_snapshots")
    # ### end Alembic commands ###
