"""fx rates for return currency basis

Revision ID: 0027
Revises: 0026
Create Date: 2026-10-04 22:45:37.421658
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

import pitquant.db.base

revision = "0027"
down_revision = "0026"
branch_labels = None
depends_on = None

ADDED_IMMUTABLE_TABLES = ("fx_rates",)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fx_rates",
        sa.Column("fx_id", sa.String(length=36), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("rate_date", sa.Date(), nullable=False),
        sa.Column("usd_per_unit", sa.Float(), nullable=False),
        sa.Column("quote_symbol", sa.String(length=20), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("source_tier", sa.String(length=12), nullable=False),
        sa.Column("quality_status", sa.String(length=24), nullable=False),
        sa.Column("available_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.Column("ingested_at", pitquant.db.base.UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("fx_id", name=op.f("pk_fx_rates")),
        sa.UniqueConstraint("currency", "rate_date", "source", name="uq_fx_rate"),
    )
    with op.batch_alter_table("fx_rates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_fx_rates_available_at"), ["available_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_fx_rates_currency"), ["currency"], unique=False)
        batch_op.create_index(batch_op.f("ix_fx_rates_rate_date"), ["rate_date"], unique=False)

    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(
                f"CREATE TRIGGER {t}_append_only BEFORE UPDATE OR DELETE ON {t} FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for t in ADDED_IMMUTABLE_TABLES:
            op.execute(f"DROP TRIGGER IF EXISTS {t}_append_only ON {t};")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("fx_rates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_fx_rates_rate_date"))
        batch_op.drop_index(batch_op.f("ix_fx_rates_currency"))
        batch_op.drop_index(batch_op.f("ix_fx_rates_available_at"))

    op.drop_table("fx_rates")
    # ### end Alembic commands ###
