"""btc independent PIT vertical

Revision ID: btc_v0_20261004
Revises: 0019
Create Date: 2026-10-04 10:41:47.303591
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

from pitquant.db.base import UTCDateTime

revision = "btc_v0_20261004"
down_revision = "0019"
branch_labels = ("btc_v0",)
depends_on = None

ADDED_IMMUTABLE_TABLES = (
    "btc_data",
    "btc_feature_snapshots",
    "btc_prediction_snapshots",
    "btc_research_records",
)
# MUST_REBASE_MIGRATIONS_BEFORE_MERGE: independent branch based on 0019.


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "btc_feature_snapshots",
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("decision_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("cohort", sa.String(length=20), nullable=False),
        sa.Column("feature_version", sa.String(length=40), nullable=False),
        sa.Column("data_version", sa.String(length=40), nullable=False),
        sa.Column("model_version", sa.String(length=60), nullable=True),
        sa.Column("strategy_version", sa.String(length=40), nullable=False),
        sa.Column("simulation_engine_version", sa.String(length=20), nullable=False),
        sa.Column("commit_sha", sa.String(length=40), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("snapshot_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("snapshot_id", name=op.f("pk_btc_feature_snapshots")),
        sa.UniqueConstraint("snapshot_hash", name=op.f("uq_btc_feature_snapshots_snapshot_hash")),
    )
    with op.batch_alter_table("btc_feature_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_btc_feature_snapshots_decision_at"), ["decision_at"], unique=False
        )

    op.create_table(
        "btc_data",
        sa.Column("datum_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=40), nullable=False),
        sa.Column("metric", sa.String(length=60), nullable=False),
        sa.Column("cohort", sa.String(length=20), nullable=False),
        sa.Column("exchange_timestamp", UTCDateTime(timezone=True), nullable=False),
        sa.Column("available_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("retrieved_at", UTCDateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("raw_hash", sa.String(length=64), nullable=False),
        sa.Column("archive_id", sa.String(length=36), nullable=False),
        sa.Column("value_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["archive_id"],
            ["raw_source_archive.archive_id"],
            name=op.f("fk_btc_data_archive_id_raw_source_archive"),
        ),
        sa.PrimaryKeyConstraint("datum_id", name=op.f("pk_btc_data")),
        sa.UniqueConstraint(
            "source",
            "metric",
            "cohort",
            "exchange_timestamp",
            "value_hash",
            name="uq_btc_data_version",
        ),
    )
    with op.batch_alter_table("btc_data", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_btc_data_available_at"), ["available_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_btc_data_exchange_timestamp"), ["exchange_timestamp"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_btc_data_metric"), ["metric"], unique=False)
        batch_op.create_index(batch_op.f("ix_btc_data_source"), ["source"], unique=False)

    op.create_table(
        "btc_prediction_snapshots",
        sa.Column("prediction_id", sa.String(length=36), nullable=False),
        sa.Column("snapshot_id", sa.String(length=36), nullable=False),
        sa.Column("horizon", sa.Integer(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("prediction_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["btc_feature_snapshots.snapshot_id"],
            name=op.f("fk_btc_prediction_snapshots_snapshot_id_btc_feature_snapshots"),
        ),
        sa.PrimaryKeyConstraint("prediction_id", name=op.f("pk_btc_prediction_snapshots")),
        sa.UniqueConstraint(
            "prediction_hash", name=op.f("uq_btc_prediction_snapshots_prediction_hash")
        ),
        sa.UniqueConstraint("snapshot_id", "horizon", name="uq_btc_prediction_horizon"),
    )
    op.create_table(
        "btc_research_records",
        sa.Column("record_id", sa.String(length=36), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("cohort", sa.String(length=20), nullable=False),
        sa.Column("prediction_id", sa.String(length=36), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("record_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", UTCDateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["prediction_id"],
            ["btc_prediction_snapshots.prediction_id"],
            name=op.f("fk_btc_research_records_prediction_id_btc_prediction_snapshots"),
        ),
        sa.PrimaryKeyConstraint("record_id", name=op.f("pk_btc_research_records")),
        sa.UniqueConstraint("record_hash", name=op.f("uq_btc_research_records_record_hash")),
    )
    with op.batch_alter_table("btc_research_records", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_btc_research_records_kind"), ["kind"], unique=False)

    # ### end Alembic commands ###

    if op.get_bind().dialect.name == "postgresql":
        for table in (
            "btc_data",
            "btc_feature_snapshots",
            "btc_prediction_snapshots",
            "btc_research_records",
        ):
            op.execute(
                f"CREATE TRIGGER {table}_append_only BEFORE UPDATE OR DELETE ON {table} "
                "FOR EACH ROW EXECUTE FUNCTION pitquant_forbid_mutation();"
            )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("btc_research_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_btc_research_records_kind"))

    op.drop_table("btc_research_records")
    op.drop_table("btc_prediction_snapshots")
    with op.batch_alter_table("btc_data", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_btc_data_source"))
        batch_op.drop_index(batch_op.f("ix_btc_data_metric"))
        batch_op.drop_index(batch_op.f("ix_btc_data_exchange_timestamp"))
        batch_op.drop_index(batch_op.f("ix_btc_data_available_at"))

    op.drop_table("btc_data")
    with op.batch_alter_table("btc_feature_snapshots", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_btc_feature_snapshots_decision_at"))

    op.drop_table("btc_feature_snapshots")
    # ### end Alembic commands ###
