// Glosario en castellano: qué es cada magnitud y cuándo suele ser positiva o negativa. Orientativo: no es consejo de inversión y ninguna cifra es una señal por sí sola.
export type Term = { t: string; q: string; p?: string; n?: string; c?: string }

const G: Record<string, Term> = {
  'posiciones simuladas': { t: 'Compras simuladas', q: 'Compras de mentira (sin broker ni dinero real) para probar una idea: eliges importe y plazo y el algoritmo revisa tu posición con reglas visibles.', p: 'Úsalas para comprobar si las revisiones habrían ayudado.', n: 'Un resultado simulado no garantiza el real.', c: 'Las recomendaciones son por reglas, sin validar con backtest: no son una predicción ni consejo de inversión.' },
  'horizonte (meses)': { t: 'Horizonte en meses', q: 'Plazo que tú te fijas para la inversión. Cambia el peso de las reglas: a plazo corto importa la tendencia del precio; a plazo largo importan más la tendencia larga, la valoración y los fundamentales.', c: 'Si cambias de plazo, la misma posición puede pasar de «mantener» a «vender».' },
  'puntuación de reglas': { t: 'Puntuación de reglas', q: 'Suma de lo que aporta cada regla (tendencia, media de 200, momentum, valoración, fundamentales, soporte), ponderada por tu horizonte.', p: 'Más de +2,5 y sin estiramiento: se podría ampliar.', n: 'Menos de −2: las reglas piden vender.', c: 'Entre medias, mantener. Los pesos y umbrales no están validados.' },
  'stop protector': { t: 'Stop protector', q: 'Precio al que la regla manda salir para limitar la pérdida. Por defecto: precio de compra menos 2 ATR (se fija al comprar).', p: 'Alejado del precio actual: margen antes de salir.', n: 'Si el precio lo toca, la recomendación es vender sin importar el resto de reglas.' },
  'trade plan': { t: 'Trade plan (plan de operación)', q: 'Una receta escrita de antemano: dónde entrar, dónde salir si sale mal (stop), dónde recoger beneficios (objetivos) y cuánto arriesgas. Se calcula con reglas sobre el precio, no con una predicción.', p: 'Relación beneficio/riesgo de 1,5R o más con un stop razonable.', n: 'Sin setup válido o con un stop muy lejano.', c: 'Es un escenario, no una garantía, y no está validado con backtest.' },
  // ── tarjetas y secciones
  fundamentals: { t: 'Fundamentales', q: 'Cifras de la empresa sacadas de sus informes oficiales (SEC): cuánto vende, cuánto gana y cuánto efectivo genera. «TTM» = suma de los últimos 12 meses.', p: 'Ingresos, beneficio y caja creciendo de forma sostenida con márgenes estables o al alza.', n: 'Ingresos o márgenes cayendo, beneficio sin caja que lo respalde, deuda creciente.', c: 'Una cifra suelta dice poco: compara con el histórico propio y con empresas del mismo sector.' },
  technicals: { t: 'Técnicos', q: 'Lectura del comportamiento del precio y del volumen: tendencia, momentum, volatilidad. Describe lo ocurrido; no predice.', p: 'Tendencia alcista (precio por encima de sus medias), volatilidad contenida, volumen que acompaña.', n: 'Precio bajo sus medias largas, caídas con mucho volumen, volatilidad disparada.', c: 'Los indicadores se contradicen con frecuencia; sirven de contexto, no de orden de compra.' },
  valuation: { t: 'Valoración', q: 'Cuánto pagas por cada euro de ventas, beneficio o caja de la empresa, comparado con su propia historia.', p: 'Múltiplos bajos frente a su historia con fundamentales sanos: «más barata» de lo habitual.', n: 'Múltiplos muy por encima de su historia sin crecimiento que lo justifique.', c: 'Barato no es lo mismo que buena inversión: puede estar barato por motivos reales.' },
  'trade plan (long)': { t: 'Plan de operación (largo)', q: 'Tu «hoja de ruta» para una operación, fijada ANTES de entrar: a qué precio comprar (zona de entrada), a cuál salir si sale mal (stop), a cuáles recoger beneficios (objetivos TP1/TP2) y cuánto arriesgas (1R = distancia entrada-stop). Se calcula con reglas sobre soportes, resistencias y ATR; no es una previsión.', p: 'Relación beneficio/riesgo de 1,5R o más y un stop razonablemente cercano.', n: 'Stop muy lejano (más de 6 ATR), poca recompensa frente al riesgo o sin setup válido.', c: 'No está validado con backtest. Nunca garantiza que el precio llegue al objetivo.' },
  prediction: { t: 'Predicción', q: 'Salida de un modelo estadístico sobre el rendimiento futuro. Hoy NO existe ningún modelo validado, por eso no se muestra ninguna cifra.', c: 'Si ves «not yet validated», no hay probabilidad ni retorno esperado: es intencionado, no un fallo.' },
  'latest filings': { t: 'Últimos documentos', q: 'Informes que la empresa presenta a la SEC: 10-K (anual), 10-Q (trimestral), 8-K (hechos relevantes).', c: 'Se muestran con la hora real en que se hicieron públicos.' },
  'technical detail': { t: 'Detalle técnico', q: 'Valores concretos de medias, MACD y bandas con los que se construye la lectura técnica.' },
  'fundamental history': { t: 'Historia fundamental', q: 'Evolución trimestral o anual de ingresos, beneficios y caja.', p: 'Líneas que suben de forma estable.', n: 'Caídas repetidas o muy irregulares.' },
  watchlist: { t: 'Lista de seguimiento', q: 'Tus valores favoritos con sus datos básicos. Se guarda solo en este navegador.' },
  holdout: { t: 'Holdout sellado', q: 'Periodo (oct-2022 → sep-2025) reservado para una evaluación final de un modelo congelado. Ningún análisis, panel ni API lo lee antes.', c: 'Es una protección contra el autoengaño: si se usa para ajustar, deja de servir.' },
  'predefined baselines': { t: 'Modelos base predefinidos', q: 'Modelos simples fijados de antemano (regresión elástica, logística) para tener una vara de medir honesta.' },
  'raw feature catalog': { t: 'Catálogo de variables', q: 'Las magnitudes (features) que un modelo podría usar, calculadas solo con datos conocidos en cada fecha.' },
  'open data gates': { t: 'Puertas de datos', q: 'Condiciones de calidad de datos que deben cumplirse antes de entrenar o evaluar modelos.', p: 'Puerta abierta: hay datos suficientes y verificados.', n: 'Puerta cerrada: no se entrena nada hasta resolverla.' },
  'research readiness gates': { t: 'Puertas de preparación', q: 'Estado, derivado de la base de datos, de cada requisito para investigar con garantías.' },
  'live reference': { t: 'Referencia en vivo', q: 'Si hay una fuente configurada para cotizaciones actuales. Sin ella se muestran barras de fin de día.' },
  providers: { t: 'Proveedores', q: 'Fuentes de datos configuradas. Las claves se leen del entorno y nunca se muestran.' },
  'engine versions': { t: 'Versiones de motor', q: 'Versión de cada cálculo, para poder reproducir un resultado exacto.' },
  summary: { t: 'Resumen', q: 'Estadísticas de las simulaciones que realmente entraron y se cerraron.', c: 'Con pocas operaciones (menos de 10) las tasas no significan nada.' },
  'price since the decision': { t: 'Precio desde la decisión', q: 'Evolución del precio tras crear la simulación, con los niveles fijados en T0 (momento de la decisión).' },
  performance: { t: 'Rendimiento', q: 'Resultado de la operación simulada: retorno, múltiplo de riesgo (R), caída máxima y comparación con el índice.', p: 'Retorno y R positivos, caída máxima pequeña.', n: 'Retorno negativo o caídas grandes antes de llegar al objetivo.' },
  timeline: { t: 'Cronología', q: 'Registro de todo lo que pasó en la operación simulada, evento a evento. Nunca se reescribe.' },
  analysis: { t: 'Análisis', q: 'Lectura de por qué la operación salió como salió, con hechos medidos; no son causas demostradas.' },
  'same bars, two plans': { t: 'Mismas barras, dos planes', q: 'Compara tu plan con el plan original sobre las mismas velas. Es un contrafactual: no es el resultado real.' },
  // ── fundamentales
  'revenue ttm': { t: 'Ingresos (12 meses)', q: 'Lo que la empresa ha vendido en los últimos 12 meses.', p: 'Crecimiento sostenido año contra año.', n: 'Ventas que se estancan o caen.' },
  'operating income ttm': { t: 'Resultado operativo (12 m)', q: 'Beneficio de la actividad principal antes de intereses e impuestos.', p: 'Creciendo más rápido que las ventas (mejora la eficiencia).', n: 'Negativo o cayendo mientras las ventas suben.' },
  'net income ttm': { t: 'Beneficio neto (12 m)', q: 'Lo que queda para los accionistas tras todos los costes, intereses e impuestos.', p: 'Positivo y creciente.', n: 'Pérdidas o beneficio que depende de partidas puntuales.' },
  'free cash flow ttm': { t: 'Caja libre (12 m)', q: 'Efectivo que genera el negocio tras pagar las inversiones necesarias. Es lo que podría repartir o reinvertir.', p: 'Positiva y cercana o superior al beneficio neto.', n: 'Negativa de forma prolongada: el negocio consume efectivo.' },
  'operating margin': { t: 'Margen operativo', q: 'Qué parte de cada euro vendido queda como beneficio operativo.', p: 'Alto y estable o subiendo: poder de fijar precios y control de costes.', n: 'Bajo o bajando: presión competitiva o de costes.', c: 'Compáralo con empresas del mismo sector.' },
  'fcf margin': { t: 'Margen de caja libre', q: 'Caja libre dividida entre ventas.', p: 'Alto y estable.', n: 'Bajo o negativo.' },
  'gross margin': { t: 'Margen bruto', q: 'Ventas menos coste directo de producir, entre ventas.', p: 'Alto y estable.', n: 'En descenso.' },
  'net margin': { t: 'Margen neto', q: 'Beneficio neto entre ventas.', p: 'Alto y estable.', n: 'Bajo, negativo o muy volátil.' },
  roa: { t: 'ROA (rentabilidad sobre activos)', q: 'Beneficio neto por cada euro de activos de la empresa.', p: 'Alto (varios % o más) y estable.', n: 'Cercano a 0 o negativo.' },
  roe: { t: 'ROE (rentabilidad sobre recursos propios)', q: 'Beneficio neto por cada euro aportado por los accionistas.', p: 'Alto con poca deuda: negocio rentable de verdad.', n: 'Bajo; ojo también si es alto solo por exceso de deuda o por tener poco capital.' },
  'gross profitability': { t: 'Rentabilidad bruta', q: 'Beneficio bruto entre activos totales: mide calidad del negocio.', p: 'Alta.', n: 'Baja.' },
  'cfo to net income': { t: 'Caja operativa / beneficio', q: 'Compara el efectivo que genera la operación con el beneficio contable.', p: 'Por encima de 1: el beneficio está respaldado por caja.', n: 'Muy por debajo de 1 de forma repetida: el beneficio puede ser «de papel».' },
  'accruals to assets': { t: 'Devengos / activos', q: 'Parte del beneficio que no es efectivo, en relación con los activos.', p: 'Cercano a 0 o negativo: beneficio de buena calidad.', n: 'Alto y positivo: beneficio apoyado en ajustes contables.' },
  'revenue cagr3': { t: 'Crecimiento anual de ingresos (3 años)', q: 'Ritmo medio anual al que han crecido las ventas en 3 años.', p: 'Positivo y constante.', n: 'Negativo o muy irregular.' },
  'operating income cagr3': { t: 'Crecimiento anual del resultado operativo (3 años)', q: 'Ritmo medio anual del beneficio operativo en 3 años.', p: 'Positivo y mayor que el de las ventas.', n: 'Negativo.' },
  'fcf cagr3': { t: 'Crecimiento anual de la caja libre (3 años)', q: 'Ritmo medio anual de la caja libre en 3 años.', p: 'Positivo.', n: 'Negativo.' },
  'asset growth1': { t: 'Crecimiento de activos (1 año)', q: 'Cuánto han crecido los activos totales en el último año.', p: 'Moderado y acompañado de más beneficio.', n: 'Muy alto de golpe: la literatura lo asocia a peores rentabilidades futuras (sobreinversión o compras caras).' },
  'capex to assets': { t: 'Inversión / activos', q: 'Inversión en inmovilizado (capex) respecto a los activos.', p: 'Inversión sostenida que luego se traduce en crecimiento.', n: 'Muy elevada sin retorno visible.' },
  'total debt': { t: 'Deuda total', q: 'Todo lo que la empresa debe a prestamistas.', p: 'Baja frente a su caja y beneficios.', n: 'Alta y creciente.' },
  'net debt': { t: 'Deuda neta', q: 'Deuda total menos efectivo.', p: 'Negativa (más caja que deuda) o baja.', n: 'Alta frente a la caja y al beneficio operativo.' },
  'debt to equity': { t: 'Deuda / recursos propios', q: 'Cuánta deuda hay por cada euro de capital de los accionistas.', p: 'Baja (menos de 1 suele ser prudente).', n: 'Alta: más riesgo si el negocio flojea o suben los tipos.' },
  'current ratio': { t: 'Ratio de liquidez', q: 'Activos a corto plazo entre deudas a corto plazo.', p: 'Por encima de 1: puede pagar lo que vence pronto.', n: 'Por debajo de 1: tensión de liquidez (puede ser normal en algunos sectores).' },
  'interest coverage': { t: 'Cobertura de intereses', q: 'Cuántas veces el resultado operativo cubre los intereses de la deuda.', p: 'Alta (más de 5 es holgada).', n: 'Menos de 2: los intereses se comen el beneficio.' },
  'shares growth1': { t: 'Variación de acciones (1 año)', q: 'Cómo ha cambiado el número de acciones en circulación.', p: 'Negativa: la empresa recompra y tu parte crece.', n: 'Positiva: dilución, tu parte se reduce.' },
  'dividend yield': { t: 'Rentabilidad por dividendo', q: 'Dividendos anuales entre el precio.', p: 'Estable y respaldado por la caja libre.', n: 'Muy alta de repente: puede indicar que el precio se ha hundido.' },
  'buyback yield': { t: 'Rentabilidad por recompras', q: 'Dinero gastado en recomprar acciones entre la capitalización.', p: 'Positiva y sostenida con caja libre.', n: 'Recompras financiadas con deuda o a precios caros.' },
  'shareholder yield': { t: 'Rentabilidad total al accionista', q: 'Dividendos más recompras netas, entre la capitalización.', p: 'Positiva y cubierta por la caja.', n: 'Negativa (emisión neta de acciones).' },
  'market cap': { t: 'Capitalización', q: 'Precio por número de acciones: lo que vale la empresa en bolsa.', c: 'Es tamaño, no calidad ni precio justo.' },
  'p/e': { t: 'PER (precio / beneficio)', q: 'Cuántos euros pagas por cada euro de beneficio anual.', p: 'Bajo frente a su historia con beneficios estables.', n: 'Muy alto sin crecimiento que lo justifique, o no calculable si hay pérdidas.' },
  'ev / sales': { t: 'EV / ventas', q: 'Valor de la empresa (capitalización más deuda neta) entre ventas.', p: 'Bajo frente a su historia.', n: 'Muy alto sin márgenes ni crecimiento que lo sostengan.' },
  // ── técnicos
  trend: { t: 'Tendencia', q: 'Dirección dominante del precio según varias reglas (medias, máximos y mínimos).', p: 'Alcista: el precio sube de forma ordenada.', n: 'Bajista: máximos y mínimos cada vez más bajos.', c: 'Operar contra una tendencia fuerte suele ser costoso.' },
  'rsi 14': { t: 'RSI 14', q: 'Oscilador de 0 a 100 que compara subidas y bajadas recientes.', p: 'Entre 40 y 70 suele indicar fuerza sana.', n: 'Más de 70 = muy estirado al alza; menos de 30 = muy debilitado.', c: 'En tendencias fuertes puede permanecer extremo mucho tiempo: no es señal por sí solo.' },
  'vs sma200': { t: 'Precio vs media de 200 sesiones', q: 'Distancia del precio a su media móvil simple de 200 días.', p: 'Positiva: precio por encima de la tendencia larga.', n: 'Negativa: por debajo.' },
  'vs sma50': { t: 'Precio vs media de 50 sesiones', q: 'Distancia del precio a su media de 50 días.', p: 'Positiva: tendencia media sana.', n: 'Negativa.' },
  'vs sma50 (atr)': { t: 'Distancia a la media 50 en ATR', q: 'La misma distancia medida en unidades de volatilidad normal (ATR).', n: 'Muy por encima (varios ATR) = estirado; muy por debajo = castigado.', p: 'Algo por encima de la media (0 a 2 ATR): tendencia sana.' },
  'vs sma20 (atr)': { t: 'Distancia a la media 20 en ATR', q: 'Distancia a la media corta medida en ATR.', n: 'Valores extremos = precio estirado respecto a lo normal.', p: 'Cerca de la media (±1 ATR): precio en equilibrio con su tendencia corta.' },
  'vs sma200 (atr)': { t: 'Distancia a la media 200 en ATR', q: 'Distancia a la media larga medida en ATR.' },
  'atr 14': { t: 'ATR 14 (rango medio)', q: 'Cuánto se mueve el precio en un día, de media, en las últimas 14 sesiones.', c: 'No es bueno ni malo: mide movimiento. Se usa para colocar el stop y dimensionar la posición.' },
  'atr %': { t: 'ATR en %', q: 'El ATR como porcentaje del precio.', p: 'Bajo: movimientos pequeños, más predecibles.', n: 'Alto: valor muy volátil, más riesgo por operación.' },
  'adx 14': { t: 'ADX 14', q: 'Mide la fuerza de la tendencia, no su dirección (0-100).', p: 'Más de 25: hay tendencia clara.', n: 'Menos de 20: mercado lateral, las señales de tendencia fallan más.' },
  'macd hist': { t: 'Histograma MACD', q: 'Diferencia entre la línea MACD y su señal: aceleración del momentum.', p: 'Positivo y creciente: momentum alcista.', n: 'Negativo y creciente en valor absoluto: momentum bajista.' },
  macd: { t: 'MACD', q: 'Diferencia entre dos medias exponenciales (12 y 26).', p: 'Por encima de su señal y de 0.', n: 'Por debajo.' },
  'macd signal': { t: 'Señal del MACD', q: 'Media de 9 sesiones del MACD; sus cruces se leen como cambios de momentum.' },
  'bollinger upper': { t: 'Banda de Bollinger superior', q: 'Media de 20 sesiones más 2 desviaciones: el precio rara vez la supera.', n: 'Tocarla repetidamente indica fuerza, pero también posible sobreextensión.', p: 'Precio dentro de las bandas y con la media subiendo: tendencia ordenada.' },
  'bollinger lower': { t: 'Banda de Bollinger inferior', q: 'Media de 20 sesiones menos 2 desviaciones.', n: 'Perforarla indica debilidad extrema.', p: 'Rebote desde la banda con volumen: posible alivio.' },
  sma20: { t: 'Media simple 20', q: 'Promedio del cierre de las últimas 20 sesiones.' },
  sma50: { t: 'Media simple 50', q: 'Promedio de las últimas 50 sesiones: tendencia media.' },
  sma200: { t: 'Media simple 200', q: 'Promedio de las últimas 200 sesiones: tendencia larga.' },
  ema20: { t: 'Media exponencial 20', q: 'Como la SMA pero da más peso a lo reciente.' },
  ema50: { t: 'Media exponencial 50', q: 'Media exponencial a 50 sesiones.' },
  '12m momentum': { t: 'Momentum 12 meses', q: 'Rentabilidad del último año (normalmente sin el último mes).', p: 'Positivo: los ganadores tienden a seguir un tiempo.', n: 'Negativo: tendencia perdedora.' },
  '52w-high distance': { t: 'Distancia al máximo de 52 semanas', q: 'Cuánto está el precio por debajo de su máximo del último año.', p: 'Cerca de 0: precio en máximos, fuerza.', n: 'Muy lejos: lleva tiempo cayendo.' },
  'volatility 63d': { t: 'Volatilidad 63 días', q: 'Cuánto oscila el precio (anualizada) en el último trimestre.', p: 'Baja: movimientos tranquilos.', n: 'Alta: riesgo y sustos mayores.' },
  'downside vol 63d': { t: 'Volatilidad a la baja', q: 'Oscilación solo de los días de caída.', p: 'Baja.', n: 'Alta: las caídas son bruscas.' },
  'max drawdown 12m': { t: 'Caída máxima 12 meses', q: 'Mayor caída desde un máximo hasta el mínimo siguiente en el último año.', p: 'Pequeña.', n: 'Grande: te habría hecho pasar un mal rato (y muchas pérdidas).' },
  'beta 252d': { t: 'Beta 252 días', q: 'Sensibilidad respecto al mercado: 1 = se mueve igual.', p: 'Menos de 1: más defensiva.', n: 'Más de 1: amplifica las caídas del mercado (y las subidas).' },
  'avg vol 20d': { t: 'Volumen medio 20 días', q: 'Acciones negociadas al día, de media.', p: 'Alto: fácil entrar y salir.', n: 'Muy bajo: puede costar vender sin mover el precio.' },
  '$ volume': { t: 'Volumen en dólares', q: 'Importe negociado al día.', p: 'Alto = liquidez.', n: 'Bajo = difícil operar sin afectar al precio.' },
  'vol ratio 20': { t: 'Volumen relativo', q: 'Volumen de hoy frente a su media de 20 días.', p: 'Por encima de 1 con subida: el movimiento tiene respaldo.', n: 'Por encima de 1 con caída fuerte: venta con convicción.' },
  'vol z-score': { t: 'Volumen anómalo (z)', q: 'Cuántas desviaciones se aleja el volumen de lo normal.', n: 'Más de 2-3: algo inusual está pasando (noticia, entrada o salida de grandes).', p: 'Cerca de 0: volumen normal, sin sorpresas.' },
  'ret 21': { t: 'Rentabilidad 1 mes (21 sesiones)', q: 'Variación del precio en las últimas 21 sesiones (≈1 mes).', p: 'Positiva.', n: 'Negativa.' },
  'ret 63': { t: 'Rentabilidad 3 meses (63 sesiones)', q: 'Variación del precio en las últimas 63 sesiones.', p: 'Positiva.', n: 'Negativa.' },
  'ret 126': { t: 'Rentabilidad 6 meses (126 sesiones)', q: 'Variación del precio en las últimas 126 sesiones.', p: 'Positiva.', n: 'Negativa.' },
  'ret 252': { t: 'Rentabilidad 12 meses (252 sesiones)', q: 'Variación del precio en el último año.', p: 'Positiva.', n: 'Negativa.' },
  'mom 12 1': { t: 'Momentum 12-1', q: 'Rentabilidad de los últimos 12 meses sin contar el último mes (evita el rebote de corto plazo).', p: 'Positivo: tendencia ganadora.', n: 'Negativo.' },
  'distance 52w high': { t: 'Distancia al máximo de 52 semanas', q: 'Cuánto está el precio por debajo de su máximo del último año.', p: 'Cerca de 0: en máximos, fuerza.', n: 'Muy lejos: lleva tiempo cayendo.' },
  // ── plan y riesgo
  'entry zone': { t: 'Zona de entrada', q: 'Rango de precios donde el plan compraría.', c: 'Si el precio no llega, la operación no se abre.' },
  stop: { t: 'Stop', q: 'Precio al que el plan sale para limitar la pérdida.', p: 'Cercano a la entrada, tras un soporte: poca pérdida si falla.', n: 'Muy lejano: la pérdida potencial es grande.' },
  'invalidation level': { t: 'Nivel de invalidación', q: 'Precio que anula la idea del plan aunque no se haya tocado el stop.', n: 'Si el precio lo cruza, la tesis ya no es válida.', p: 'Lejos del precio actual: la idea tiene margen antes de anularse.' },
  'structural target': { t: 'Objetivo estructural', q: 'Próxima resistencia relevante, usada como primer objetivo.' },
  'risk / share': { t: 'Riesgo por acción', q: 'Distancia entre entrada y stop, por acción.', p: 'Pequeña frente al objetivo.', n: 'Grande frente al objetivo: la operación compensa poco.' },
  'risk amount': { t: 'Importe en riesgo', q: 'Dinero que perderías si salta el stop, según tu capital y % de riesgo.' },
  notional: { t: 'Importe de la posición', q: 'Valor total de las acciones que compras en la simulación.' },
  'max shares': { t: 'Acciones máximas', q: 'Número de acciones que puedes comprar arriesgando solo lo elegido.' },
  'actual risk': { t: 'Riesgo real', q: 'Riesgo efectivo con el número entero de acciones calculado.' },
  r: { t: 'R (múltiplo de riesgo)', q: 'Ganancia o pérdida medida en veces el riesgo inicial: +2R = ganas el doble de lo que arriesgabas.', p: 'Positivo; media por encima de 0 con muchas operaciones.', n: 'Negativo; −1R = stop alcanzado.' },
  mae: { t: 'MAE (peor momento)', q: 'Mayor pérdida latente que tuvo la operación mientras estuvo abierta.', n: 'Alto: el stop estuvo cerca o la operación fue incómoda.', p: 'Bajo: la operación casi no sufrió.' },
  mfe: { t: 'MFE (mejor momento)', q: 'Mayor ganancia latente que llegó a tener la operación.', c: 'Si es mucho mayor que el resultado final, quizá se dejó escapar beneficio.', p: 'Alto y capturado en el resultado: el plan sacó partido.', n: 'Muy superior al resultado final: se devolvió beneficio.' },
  drawdown: { t: 'Caída máxima (drawdown)', q: 'Mayor caída desde un máximo de la curva de resultados.', p: 'Pequeña.', n: 'Grande: la estrategia es difícil de aguantar.' },
  // ── predicción
  'p(outperform)': { t: 'P(supera al índice)', q: 'Probabilidad estimada por un modelo de batir al índice.', c: 'Solo tiene sentido con un modelo validado y calibrado. Hoy no existe.' },
  'expected excess return': { t: 'Exceso de retorno esperado', q: 'Retorno que un modelo espera por encima del índice.', c: 'Mostrado solo con un modelo validado.' },
  'p10 / p50 / p90': { t: 'Rango de resultados', q: 'Escenario malo (10 %), central (50 %) y bueno (90 %) del modelo.' },
  'confidence · calibration': { t: 'Confianza y calibración', q: 'Cuánto se fía el modelo y si sus probabilidades se cumplen históricamente.' },
}

const norm = (s: string) => s.toLowerCase().replace(/_/g, ' ').replace(/\s+/g, ' ').trim()
const ALIAS: [RegExp, string][] = [
  [/^entry \(.+\)$/, 'entry zone'],
]

export function lookup(label: unknown): Term | undefined {
  if (typeof label !== 'string') return undefined
  const k = norm(label)
  if (G[k]) return G[k]
  const hit = ALIAS.find(([re]) => re.test(k))
  return hit ? G[hit[1]] : undefined
}
export const GLOSSARY = G
